// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/auction"
	"github.com/bidon-io/bidon-backend/internal/sdkapi"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/schema"
	"sync"
)

// Ensure, that StatsV2NotificationHandlerMock does implement sdkapi.StatsV2NotificationHandler.
// If this is not the case, regenerate this file with moq.
var _ sdkapi.StatsV2NotificationHandler = &StatsV2NotificationHandlerMock{}

// StatsV2NotificationHandlerMock is a mock implementation of sdkapi.StatsV2NotificationHandler.
//
//	func TestSomethingThatUsesStatsV2NotificationHandler(t *testing.T) {
//
//		// make and configure a mocked sdkapi.StatsV2NotificationHandler
//		mockedStatsV2NotificationHandler := &StatsV2NotificationHandlerMock{
//			HandleStatsV2Func: func(contextMoqParam context.Context, statsV2 schema.StatsV2, config *auction.Config, s1 string, s2 string)  {
//				panic("mock out the HandleStatsV2 method")
//			},
//		}
//
//		// use mockedStatsV2NotificationHandler in code that requires sdkapi.StatsV2NotificationHandler
//		// and then make assertions.
//
//	}
type StatsV2NotificationHandlerMock struct {
	// HandleStatsV2Func mocks the HandleStatsV2 method.
	HandleStatsV2Func func(contextMoqParam context.Context, statsV2 schema.StatsV2, config *auction.Config, s1 string, s2 string)

	// calls tracks calls to the methods.
	calls struct {
		// HandleStatsV2 holds details about calls to the HandleStatsV2 method.
		HandleStatsV2 []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// StatsV2 is the statsV2 argument value.
			StatsV2 schema.StatsV2
			// Config is the config argument value.
			Config *auction.Config
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
	}
	lockHandleStatsV2 sync.RWMutex
}

// HandleStatsV2 calls HandleStatsV2Func.
func (mock *StatsV2NotificationHandlerMock) HandleStatsV2(contextMoqParam context.Context, statsV2 schema.StatsV2, config *auction.Config, s1 string, s2 string) {
	if mock.HandleStatsV2Func == nil {
		panic("StatsV2NotificationHandlerMock.HandleStatsV2Func: method is nil but StatsV2NotificationHandler.HandleStatsV2 was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		StatsV2         schema.StatsV2
		Config          *auction.Config
		S1              string
		S2              string
	}{
		ContextMoqParam: contextMoqParam,
		StatsV2:         statsV2,
		Config:          config,
		S1:              s1,
		S2:              s2,
	}
	mock.lockHandleStatsV2.Lock()
	mock.calls.HandleStatsV2 = append(mock.calls.HandleStatsV2, callInfo)
	mock.lockHandleStatsV2.Unlock()
	mock.HandleStatsV2Func(contextMoqParam, statsV2, config, s1, s2)
}

// HandleStatsV2Calls gets all the calls that were made to HandleStatsV2.
// Check the length with:
//
//	len(mockedStatsV2NotificationHandler.HandleStatsV2Calls())
func (mock *StatsV2NotificationHandlerMock) HandleStatsV2Calls() []struct {
	ContextMoqParam context.Context
	StatsV2         schema.StatsV2
	Config          *auction.Config
	S1              string
	S2              string
} {
	var calls []struct {
		ContextMoqParam context.Context
		StatsV2         schema.StatsV2
		Config          *auction.Config
		S1              string
		S2              string
	}
	mock.lockHandleStatsV2.RLock()
	calls = mock.calls.HandleStatsV2
	mock.lockHandleStatsV2.RUnlock()
	return calls
}
