### Config
POST {{sdkapiHost}}/v2/config
Content-Type: application/json
X-Bidon-Version: 0.6.0

< ./internal/sdkapi/v2/apihandlers/testdata/config/adikteev_config_request.json


### Auction banner — iOS
POST {{sdkapiHost}}/v2/auction/banner
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/ios_adikteev_banner.json

### Auction banner — Android
POST {{sdkapiHost}}/v2/auction/banner
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/android_adikteev_banner.json

### Auction banner — iOS MREC
POST {{sdkapiHost}}/v2/auction/banner
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/ios_adikteev_banner_mrec.json

### Auction banner — Android MREC
POST {{sdkapiHost}}/v2/auction/banner
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/android_adikteev_banner_mrec.json

### Auction interstitial — iOS
POST {{sdkapiHost}}/v2/auction/interstitial
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/ios_adikteev_interstitial.json

### Auction interstitial — Android
POST {{sdkapiHost}}/v2/auction/interstitial
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/android_adikteev_interstitial.json

### Auction rewarded — iOS
POST {{sdkapiHost}}/v2/auction/rewarded
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/ios_adikteev_rewarded.json

### Auction rewarded — Android
POST {{sdkapiHost}}/v2/auction/rewarded
Content-Type: application/json
X-Bidon-Version: 0.6.0
X-Forwarded-For: 94.24.105.28

< ./internal/sdkapi/v2/apihandlers/testdata/auction/adikteev/android_adikteev_rewarded.json
