// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetConfigJSONBodyDeviceConnectionType.
const (
	CELLULAR        GetConfigJSONBodyDeviceConnectionType = "CELLULAR"
	CELLULAR2G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_2_G"
	CELLULAR3G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_3_G"
	CELLULAR4G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_4_G"
	CELLULAR5G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_5_G"
	CELLULARUNKNOWN GetConfigJSONBodyDeviceConnectionType = "CELLULAR_UNKNOWN"
	ETHERNET        GetConfigJSONBodyDeviceConnectionType = "ETHERNET"
	WIFI            GetConfigJSONBodyDeviceConnectionType = "WIFI"
)

// Defines values for GetConfigJSONBodyDeviceType.
const (
	PHONE  GetConfigJSONBodyDeviceType = "PHONE"
	TABLET GetConfigJSONBodyDeviceType = "TABLET"
)

// GetConfigJSONBody defines parameters for GetConfig.
type GetConfigJSONBody struct {
	Adapters *map[string]struct {
		SdkVersion string `json:"sdk_version"`
		Version    string `json:"version"`
	} `json:"adapters,omitempty"`
	App *struct {
		// Bundle The bundle identifier of the application, typically in reverse domain name notation (e.g., com.example.myapp).
		Bundle string `json:"bundle"`

		// Framework The name of the framework used by the application (e.g., React Native, Flutter, etc.).
		Framework string `json:"framework"`

		// FrameworkVersion The version of the framework used by the application, specifying compatibility.
		FrameworkVersion *string `json:"framework_version,omitempty"`

		// Key A unique key or identifier for the application.
		Key string `json:"key"`

		// PluginVersion The version of the plugin integrated into the application
		PluginVersion *string `json:"plugin_version,omitempty"`

		// SdkVersion The version of the SDK used in the application.
		SdkVersion *string `json:"sdk_version,omitempty"`

		// Skadn An array of SKAdNetwork IDs for ad attribution, used primarily for iOS applications.
		Skadn *[]string `json:"skadn,omitempty"`

		// Version The version of the application, typically following semantic versioning (e.g., 1.0.0).
		Version string `json:"version"`
	} `json:"app,omitempty"`
	Device *struct {
		// Carrier Carrier
		Carrier *string `json:"carrier,omitempty"`

		// ConnectionType Connection Type
		ConnectionType GetConfigJSONBodyDeviceConnectionType `json:"connection_type"`
		Geo            *struct {
			// Accuracy Accuracy of the location data
			Accuracy *float32 `json:"accuracy,omitempty"`

			// City City name
			City *string `json:"city,omitempty"`

			// Country Country code or name
			Country *string `json:"country,omitempty"`

			// Lastfix Timestamp of the last location fix in seconds since epoch
			Lastfix *int `json:"lastfix,omitempty"`

			// Lat Latitude of the location
			Lat *float32 `json:"lat,omitempty"`

			// Lon Longitude of the location
			Lon *float32 `json:"lon,omitempty"`

			// Utcoffset UTC offset in minutes
			Utcoffset *int `json:"utcoffset,omitempty"`

			// Zip ZIP or postal code
			Zip *string `json:"zip,omitempty"`
		} `json:"geo,omitempty"`

		// H Height
		H int `json:"h"`

		// Hwv Hardware Version
		Hwv string `json:"hwv"`

		// Js JavaScript support
		Js int `json:"js"`

		// Language Language
		Language string `json:"language"`

		// Make Manufacturer
		Make string `json:"make"`

		// Mccmnc Mobile Country Code and Mobile Network Code
		Mccmnc *string `json:"mccmnc,omitempty"`

		// Model Model
		Model string `json:"model"`

		// Os Operating System
		Os string `json:"os"`

		// Osv Operating System Version
		Osv string `json:"osv"`

		// Ppi Pixels per Inch (PPI)
		Ppi int `json:"ppi"`

		// Pxratio Pixel Ratio
		Pxratio float32 `json:"pxratio"`

		// Type Device Type
		Type *GetConfigJSONBodyDeviceType `json:"type,omitempty"`

		// Ua UserAgent
		Ua string `json:"ua"`

		// W Width
		W int `json:"w"`
	} `json:"device,omitempty"`
	Ext *string `json:"ext,omitempty"`
	Geo *struct {
		// Accuracy Accuracy of the location data
		Accuracy *float32 `json:"accuracy,omitempty"`

		// City City name
		City *string `json:"city,omitempty"`

		// Country Country code or name
		Country *string `json:"country,omitempty"`

		// Lastfix Timestamp of the last location fix in seconds since epoch
		Lastfix *int `json:"lastfix,omitempty"`

		// Lat Latitude of the location
		Lat *float32 `json:"lat,omitempty"`

		// Lon Longitude of the location
		Lon *float32 `json:"lon,omitempty"`

		// Utcoffset UTC offset in minutes
		Utcoffset *int `json:"utcoffset,omitempty"`

		// Zip ZIP or postal code
		Zip *string `json:"zip,omitempty"`
	} `json:"geo,omitempty"`
	Regs *struct {
		// Coppa Indicates if COPPA regulations apply
		Coppa *bool `json:"coppa,omitempty"`

		// EuPrivacy EU privacy string indicating compliance
		EuPrivacy *string `json:"eu_privacy,omitempty"`

		// Gdpr Indicates if GDPR regulations apply
		Gdpr *bool `json:"gdpr,omitempty"`

		// Iab IAB-specific settings or values
		Iab *map[string]interface{} `json:"iab,omitempty"`

		// UsPrivacy US privacy string indicating compliance
		UsPrivacy *string `json:"us_privacy,omitempty"`
	} `json:"regs,omitempty"`
	Session *struct {
		// Battery Battery level percentage
		Battery float32 `json:"battery"`

		// CpuUsage CPU usage percentage
		CpuUsage float32 `json:"cpu_usage"`

		// Id Unique identifier for the session
		Id openapi_types.UUID `json:"id"`

		// LaunchMonotonicTs Monotonic timestamp of the session launch
		LaunchMonotonicTs int `json:"launch_monotonic_ts"`

		// LaunchTs Timestamp of the session launch
		LaunchTs int `json:"launch_ts"`

		// MemoryWarningsMonotonicTs Monotonic timestamps when memory warnings occurred
		MemoryWarningsMonotonicTs []int `json:"memory_warnings_monotonic_ts"`

		// MemoryWarningsTs Timestamps when memory warnings occurred
		MemoryWarningsTs []int `json:"memory_warnings_ts"`

		// MonotonicTs Current monotonic timestamp of the session
		MonotonicTs int `json:"monotonic_ts"`

		// RamSize Total size of RAM
		RamSize int `json:"ram_size"`

		// RamUsed Amount of RAM used
		RamUsed int `json:"ram_used"`

		// StartMonotonicTs Monotonic timestamp of the session start
		StartMonotonicTs int `json:"start_monotonic_ts"`

		// StartTs Timestamp of the session start
		StartTs int `json:"start_ts"`

		// StorageFree Free storage space available
		StorageFree *int `json:"storage_free,omitempty"`

		// StorageUsed Used storage space
		StorageUsed *int `json:"storage_used,omitempty"`

		// Ts Current timestamp of the session
		Ts int `json:"ts"`
	} `json:"session,omitempty"`
	Token *string `json:"token,omitempty"`
	User  *struct {
		// Consent Consent settings or preferences
		Consent *map[string]interface{} `json:"consent,omitempty"`

		// Coppa Indicates if COPPA (Children's Online Privacy Protection Act) applies
		Coppa *bool `json:"coppa,omitempty"`

		// Idfa Identifier for Advertisers (IDFA)
		Idfa *openapi_types.UUID `json:"idfa,omitempty"`

		// Idfv Identifier for Vendors (IDFV)
		Idfv *openapi_types.UUID `json:"idfv,omitempty"`

		// Idg Generic identifier (IDG)
		Idg *openapi_types.UUID `json:"idg,omitempty"`

		// TrackingAuthorizationStatus Status of tracking authorization
		TrackingAuthorizationStatus string `json:"tracking_authorization_status"`
	} `json:"user,omitempty"`
}

// GetConfigJSONBodyDeviceConnectionType defines parameters for GetConfig.
type GetConfigJSONBodyDeviceConnectionType string

// GetConfigJSONBodyDeviceType defines parameters for GetConfig.
type GetConfigJSONBodyDeviceType string

// GetConfigJSONRequestBody defines body for GetConfig for application/json ContentType.
type GetConfigJSONRequestBody GetConfigJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get config
	// (POST /v2/config)
	GetConfig(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetConfig(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v2/config", wrapper.GetConfig)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RaW2/bOvL/KoT+Bf4tVrFz0rP74DfHSVNvcxIjlxbYRWHQ1EhmI5E85MiJe+DvviAp",
	"2bRNX9ptsG8WOXf+Zjgk/VfCZKWkAIEm6f2VGDaFirqfNKMKQdufb3iW9JJuM9ltZjr+u/PNSJGkyRv/",
	"mfSSKaIyvW7XTpw0RFIX3UzTHLtnp2enJ7+dNdKSNFFaKtDIwVuQPY1noA2Xwn7iXEHSSwxqLopkkSa7",
	"5xZpouHPmmvIkt6/l4TpmsivacsmJ9+AoRVJlVp5SZV6HccmtchKsL8yMExzhc6N5GEKxM8RnoFAnnPQ",
	"ROYEp0CoUiVn1JKmBOeKM1qWc8IF0WBdApLJinJBBK2ACImOlLyFTtFJCZNVB15opUroVHOq1LtOkm6H",
	"NNe0gmepn+LGOdGNPUtSUhvIyGS+aWWr+g4oQ3JDkc8gJR/KGhF0SgBZ54AR4epvG9NMHm1PSowCxvM5",
	"F4WNh6LIJ7zkOI9a8QTzbb19Ugv+Zw3kCeZE6nCZcqk3NUblqrIuuPgh1zwL4QKh0BQhsz/lpraYso0U",
	"Oqjp/uKTDx8XRzljnmgWkdwXhGpN51bs/ad+dgPoVmZ4YVycaEYoouaT2i+MU6k0r6jm5dyR8Nv7ULux",
	"6jlCZaKloBlwSjdKw0GfdyRWLstSPlusGKioQM5aRjvWYPu3zmnnNIbijQrUZLxHVZhmK1Nj5WjCs4yL",
	"4oRJkfNiVZnWx1+nSKF8AjFGXoGscezjvh3LZp5ktfZJ36aBY7cwqnhZcgNMiswtYi51RTHpJVzgP35f",
	"Rc6hG7QLHXK09TE5936Sgfc/EiEfgRMbazC4itD6+OtEqNn8mt8Zt/7TcrRG80ZDnvSS/+uuNtfNzTPA",
	"7/ZGtI9dKUuZwYwzOETcUC3SBF4wmkIFyENCLIkDdnHQNw1FXfrMdXUCTJuP+7haMhsRi5+oobVpWpE9",
	"ghzNYrEPMEZJYSCCGD/xqyATB0ZOSwNbbYFH+yHfNorCIk244HiIy9IELKqkDKq212sLa6SSGigs2eGV",
	"82R7Vm6xDlYXdP/9OunJqNbcQ2W9bg2aich+xqQQwCzd2M9t8S4JyIMlSBMQdWVL/OXDx8u7m8uHJE2+",
	"DD8MkzQZXF5fP17374Kf48ebTze3X27CobPxVfj5fv3z9/XPv4+vgp3iZ7J3uu3UR+DFFCOlOE2mz7MI",
	"PdXZM9VAPi8b6y2DvkU2jH/SGb1338TUSkkd11lSUdS0iET/up2JKKzoU4TjDyrqnDKsdXzBK8YqwSJ8",
	"csJLIANZC9RzMpAZECoy0oy3DY0dj4qVGZQxqXY4Qi8j0bpVYPdUUZD7uUGo4nyzw4z7lkkpvi1gxF+g",
	"NESBJkPBpuTtaDR8F10q9eK2/R0iyJ2bXDKKupqE+90m04WrBpuJNfp4e3OZpMlD//z68iGK/ppuC3s0",
	"oPuFrUkRhudt+i88w2m8HQk7udoWGoe1dpXd6vml8Plic8yq8NFdBcklRQDv7XLzddX6+FjEWp421V0B",
	"LUC+UnPDWK0pi52Bmpm2fy5lc97LKNLYYjOOETEDjnN3oIzXYZd3sfrrE5LZhJR6p4CSGsz5S6Rp5RUY",
	"pJVamk8NrnzI+YttWpt+lRguGBBQkk13lCqMVSnkWGewGaBYbMrYIeVaiuJoCTUymecGIoY8PgyIn/ON",
	"uKgRTNSP71xts/9rOLIhVtIgLV3Eo+ecFrFXIGNwDRuPJWyDwf9Bo3VE4x5rHbGiDlDHnGDCkuH40pXW",
	"IMuHguOe003YRS9jFwy+UuMklYoU1KHI7DEZDOE5GdyORn0SmOKO0fOVExMpS6CulYd6rDSfRYvJ5SNp",
	"5oiHFOFeTXtJU3IqWDTFi0zpA1ZeXYzujjSS08luOKCuId1U1D8/8RdKnBEDaC02Nl9mtKzDNFstZ212",
	"B+Lx/icDEWTgXQCXiPqwlXdIagZeB0XNOXPrYgheEITxtRbKrLkPaqNOuPDpZQnoRNboCmBraQwH1pXY",
	"MTE6HkTrvglHNFKr42oTKTfwStfBFBFim925nyAlzKC07RgDgWvtb7DJqnpcm2jXPBg9Ejd1QIQP2AYs",
	"/XVn5J6zjVFwo1PbmEc341qw6biSQqIUnI3RxHrjZtbdKa1t0Y0q4uXs2Iidipjgh58QV0El9Xz8TLWw",
	"af3jphvyPAVBvBzSyiHS9k52W9i+zAy0b57BN63Z6+Wv1bzX74GVKJBUB5cuGmRNq7Hh32MPIdJ2HHbO",
	"yrnr/7GTvzYQQW2/sm1iw+tul6MCDFKN/z0snZg9Cn4IlPuESU0LGOcaIiH7oAFIQ0KMogwInVFe0kkJ",
	"e8XFI/hoIFsXFxWyDxU/gIWNhslVkVVGxwtIEN3oSjrjNhAcTaUD2R7gLIBsuqzaYen9Gu4uG86GbUD4",
	"lmq/XquPE6bZ749vawaeaa2jURpy0CBYvK05vl98O5jyMtMg/t+QW1FyAWTUND0jLbG5WOszfOdfZUJ9",
	"Ya+W5TF963tUP5tZPw1oQ94OLz703x2zVfEsnx0U/RlEJhuxn48UW2xLvQIBmrNwc307vLg6SiBqyp64",
	"KMa0xqnU/LvrmMYGKdaRnLx34y4RG0ayxnjwAWu/vgD3jya8aGtBsnAHwdxdXCwz5OIT6Y+GwRNYL3Hv",
	"ae5iS4Ggiie95H3ntPPeYpvi1HnWnZ11V+dJezr1/ua0LrHBPba4X73tdZWWkxKqv7kkW/7BIbg17Syv",
	"SkFruZ6Uze312tHFEjW2+sevYeZWFZcHuub56Vxm8z2G7TQoeo278eIVMcyrJy1FuJA2493K+kcOF8+z",
	"09Nfb1zzurLPuiVJmpi6qqjtgG30SPtKsVgs/hMAAP//6YQFYZUiAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
