// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package admin

import (
	"context"
	"sync"
)

// Ensure, that ResourceRepoMock does implement ResourceRepo.
// If this is not the case, regenerate this file with moq.
var _ ResourceRepo[any, any] = &ResourceRepoMock[any, any]{}

// ResourceRepoMock is a mock implementation of ResourceRepo.
//
//	func TestSomethingThatUsesResourceRepo(t *testing.T) {
//
//		// make and configure a mocked ResourceRepo
//		mockedResourceRepo := &ResourceRepoMock{
//			CreateFunc: func(ctx context.Context, attrs *ResourceAttrs) (*Resource, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			FindFunc: func(ctx context.Context, id int64) (*Resource, error) {
//				panic("mock out the Find method")
//			},
//			ListFunc: func(ctx context.Context) ([]Resource, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, attrs *ResourceAttrs) (*Resource, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedResourceRepo in code that requires ResourceRepo
//		// and then make assertions.
//
//	}
type ResourceRepoMock[Resource any, ResourceAttrs any] struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, attrs *ResourceAttrs) (*Resource, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id int64) (*Resource, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]Resource, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, attrs *ResourceAttrs) (*Resource, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Attrs is the attrs argument value.
			Attrs *ResourceAttrs
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Attrs is the attrs argument value.
			Attrs *ResourceAttrs
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockFind   sync.RWMutex
	lockList   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) Create(ctx context.Context, attrs *ResourceAttrs) (*Resource, error) {
	if mock.CreateFunc == nil {
		panic("ResourceRepoMock.CreateFunc: method is nil but ResourceRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Attrs *ResourceAttrs
	}{
		Ctx:   ctx,
		Attrs: attrs,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, attrs)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedResourceRepo.CreateCalls())
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) CreateCalls() []struct {
	Ctx   context.Context
	Attrs *ResourceAttrs
} {
	var calls []struct {
		Ctx   context.Context
		Attrs *ResourceAttrs
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("ResourceRepoMock.DeleteFunc: method is nil but ResourceRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedResourceRepo.DeleteCalls())
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) Find(ctx context.Context, id int64) (*Resource, error) {
	if mock.FindFunc == nil {
		panic("ResourceRepoMock.FindFunc: method is nil but ResourceRepo.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedResourceRepo.FindCalls())
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) FindCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) List(ctx context.Context) ([]Resource, error) {
	if mock.ListFunc == nil {
		panic("ResourceRepoMock.ListFunc: method is nil but ResourceRepo.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedResourceRepo.ListCalls())
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) Update(ctx context.Context, id int64, attrs *ResourceAttrs) (*Resource, error) {
	if mock.UpdateFunc == nil {
		panic("ResourceRepoMock.UpdateFunc: method is nil but ResourceRepo.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		Attrs *ResourceAttrs
	}{
		Ctx:   ctx,
		ID:    id,
		Attrs: attrs,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, attrs)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedResourceRepo.UpdateCalls())
func (mock *ResourceRepoMock[Resource, ResourceAttrs]) UpdateCalls() []struct {
	Ctx   context.Context
	ID    int64
	Attrs *ResourceAttrs
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		Attrs *ResourceAttrs
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that AuthContextMock does implement AuthContext.
// If this is not the case, regenerate this file with moq.
var _ AuthContext = &AuthContextMock{}

// AuthContextMock is a mock implementation of AuthContext.
//
//	func TestSomethingThatUsesAuthContext(t *testing.T) {
//
//		// make and configure a mocked AuthContext
//		mockedAuthContext := &AuthContextMock{
//			IsAdminFunc: func() bool {
//				panic("mock out the IsAdmin method")
//			},
//			UserIDFunc: func() int64 {
//				panic("mock out the UserID method")
//			},
//		}
//
//		// use mockedAuthContext in code that requires AuthContext
//		// and then make assertions.
//
//	}
type AuthContextMock struct {
	// IsAdminFunc mocks the IsAdmin method.
	IsAdminFunc func() bool

	// UserIDFunc mocks the UserID method.
	UserIDFunc func() int64

	// calls tracks calls to the methods.
	calls struct {
		// IsAdmin holds details about calls to the IsAdmin method.
		IsAdmin []struct {
		}
		// UserID holds details about calls to the UserID method.
		UserID []struct {
		}
	}
	lockIsAdmin sync.RWMutex
	lockUserID  sync.RWMutex
}

// IsAdmin calls IsAdminFunc.
func (mock *AuthContextMock) IsAdmin() bool {
	if mock.IsAdminFunc == nil {
		panic("AuthContextMock.IsAdminFunc: method is nil but AuthContext.IsAdmin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsAdmin.Lock()
	mock.calls.IsAdmin = append(mock.calls.IsAdmin, callInfo)
	mock.lockIsAdmin.Unlock()
	return mock.IsAdminFunc()
}

// IsAdminCalls gets all the calls that were made to IsAdmin.
// Check the length with:
//
//	len(mockedAuthContext.IsAdminCalls())
func (mock *AuthContextMock) IsAdminCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsAdmin.RLock()
	calls = mock.calls.IsAdmin
	mock.lockIsAdmin.RUnlock()
	return calls
}

// UserID calls UserIDFunc.
func (mock *AuthContextMock) UserID() int64 {
	if mock.UserIDFunc == nil {
		panic("AuthContextMock.UserIDFunc: method is nil but AuthContext.UserID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockUserID.Lock()
	mock.calls.UserID = append(mock.calls.UserID, callInfo)
	mock.lockUserID.Unlock()
	return mock.UserIDFunc()
}

// UserIDCalls gets all the calls that were made to UserID.
// Check the length with:
//
//	len(mockedAuthContext.UserIDCalls())
func (mock *AuthContextMock) UserIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUserID.RLock()
	calls = mock.calls.UserID
	mock.lockUserID.RUnlock()
	return calls
}

// Ensure, that resourcePolicyMock does implement resourcePolicy.
// If this is not the case, regenerate this file with moq.
var _ resourcePolicy[any, any] = &resourcePolicyMock[any, any]{}

// resourcePolicyMock is a mock implementation of resourcePolicy.
//
//	func TestSomethingThatUsesresourcePolicy(t *testing.T) {
//
//		// make and configure a mocked resourcePolicy
//		mockedresourcePolicy := &resourcePolicyMock{
//			scopeFunc: func(authContext AuthContext) (resourceScope[Resource], error) {
//				panic("mock out the scope method")
//			},
//		}
//
//		// use mockedresourcePolicy in code that requires resourcePolicy
//		// and then make assertions.
//
//	}
type resourcePolicyMock[Resource any, ResourceAttrs any] struct {
	// scopeFunc mocks the scope method.
	scopeFunc func(authContext AuthContext) (resourceScope[Resource], error)

	// calls tracks calls to the methods.
	calls struct {
		// scope holds details about calls to the scope method.
		scope []struct {
			// AuthContext is the authContext argument value.
			AuthContext AuthContext
		}
	}
	lockscope sync.RWMutex
}

// scope calls scopeFunc.
func (mock *resourcePolicyMock[Resource, ResourceAttrs]) scope(authContext AuthContext) (resourceScope[Resource], error) {
	if mock.scopeFunc == nil {
		panic("resourcePolicyMock.scopeFunc: method is nil but resourcePolicy.scope was just called")
	}
	callInfo := struct {
		AuthContext AuthContext
	}{
		AuthContext: authContext,
	}
	mock.lockscope.Lock()
	mock.calls.scope = append(mock.calls.scope, callInfo)
	mock.lockscope.Unlock()
	return mock.scopeFunc(authContext)
}

// scopeCalls gets all the calls that were made to scope.
// Check the length with:
//
//	len(mockedresourcePolicy.scopeCalls())
func (mock *resourcePolicyMock[Resource, ResourceAttrs]) scopeCalls() []struct {
	AuthContext AuthContext
} {
	var calls []struct {
		AuthContext AuthContext
	}
	mock.lockscope.RLock()
	calls = mock.calls.scope
	mock.lockscope.RUnlock()
	return calls
}

// Ensure, that resourceScopeMock does implement resourceScope.
// If this is not the case, regenerate this file with moq.
var _ resourceScope[any] = &resourceScopeMock[any]{}

// resourceScopeMock is a mock implementation of resourceScope.
//
//	func TestSomethingThatUsesresourceScope(t *testing.T) {
//
//		// make and configure a mocked resourceScope
//		mockedresourceScope := &resourceScopeMock{
//			findFunc: func(contextMoqParam context.Context, n int64) (*Resource, error) {
//				panic("mock out the find method")
//			},
//			listFunc: func(contextMoqParam context.Context) ([]Resource, error) {
//				panic("mock out the list method")
//			},
//		}
//
//		// use mockedresourceScope in code that requires resourceScope
//		// and then make assertions.
//
//	}
type resourceScopeMock[Resource any] struct {
	// findFunc mocks the find method.
	findFunc func(contextMoqParam context.Context, n int64) (*Resource, error)

	// listFunc mocks the list method.
	listFunc func(contextMoqParam context.Context) ([]Resource, error)

	// calls tracks calls to the methods.
	calls struct {
		// find holds details about calls to the find method.
		find []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int64
		}
		// list holds details about calls to the list method.
		list []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockfind sync.RWMutex
	locklist sync.RWMutex
}

// find calls findFunc.
func (mock *resourceScopeMock[Resource]) find(contextMoqParam context.Context, n int64) (*Resource, error) {
	if mock.findFunc == nil {
		panic("resourceScopeMock.findFunc: method is nil but resourceScope.find was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int64
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
	}
	mock.lockfind.Lock()
	mock.calls.find = append(mock.calls.find, callInfo)
	mock.lockfind.Unlock()
	return mock.findFunc(contextMoqParam, n)
}

// findCalls gets all the calls that were made to find.
// Check the length with:
//
//	len(mockedresourceScope.findCalls())
func (mock *resourceScopeMock[Resource]) findCalls() []struct {
	ContextMoqParam context.Context
	N               int64
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int64
	}
	mock.lockfind.RLock()
	calls = mock.calls.find
	mock.lockfind.RUnlock()
	return calls
}

// list calls listFunc.
func (mock *resourceScopeMock[Resource]) list(contextMoqParam context.Context) ([]Resource, error) {
	if mock.listFunc == nil {
		panic("resourceScopeMock.listFunc: method is nil but resourceScope.list was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.locklist.Lock()
	mock.calls.list = append(mock.calls.list, callInfo)
	mock.locklist.Unlock()
	return mock.listFunc(contextMoqParam)
}

// listCalls gets all the calls that were made to list.
// Check the length with:
//
//	len(mockedresourceScope.listCalls())
func (mock *resourceScopeMock[Resource]) listCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.locklist.RLock()
	calls = mock.calls.list
	mock.locklist.RUnlock()
	return calls
}
