// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateAppJSONBodyPlatformId.
const (
	CreateAppJSONBodyPlatformIdAndroid CreateAppJSONBodyPlatformId = "android"
	CreateAppJSONBodyPlatformIdIos     CreateAppJSONBodyPlatformId = "ios"
)

// Defines values for UpdateAppJSONBodyPlatformId.
const (
	UpdateAppJSONBodyPlatformIdAndroid UpdateAppJSONBodyPlatformId = "android"
	UpdateAppJSONBodyPlatformIdIos     UpdateAppJSONBodyPlatformId = "ios"
)

// Defines values for CreateAuctionConfigurationJSONBodyAdType.
const (
	CreateAuctionConfigurationJSONBodyAdTypeBanner       CreateAuctionConfigurationJSONBodyAdType = "banner"
	CreateAuctionConfigurationJSONBodyAdTypeInterstitial CreateAuctionConfigurationJSONBodyAdType = "interstitial"
	CreateAuctionConfigurationJSONBodyAdTypeRewarded     CreateAuctionConfigurationJSONBodyAdType = "rewarded"
)

// Defines values for UpdateAuctionConfigurationJSONBodyAdType.
const (
	UpdateAuctionConfigurationJSONBodyAdTypeBanner       UpdateAuctionConfigurationJSONBodyAdType = "banner"
	UpdateAuctionConfigurationJSONBodyAdTypeInterstitial UpdateAuctionConfigurationJSONBodyAdType = "interstitial"
	UpdateAuctionConfigurationJSONBodyAdTypeRewarded     UpdateAuctionConfigurationJSONBodyAdType = "rewarded"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyAdType.
const (
	CreateAuctionConfigurationV2JSONBodyAdTypeBanner       CreateAuctionConfigurationV2JSONBodyAdType = "banner"
	CreateAuctionConfigurationV2JSONBodyAdTypeInterstitial CreateAuctionConfigurationV2JSONBodyAdType = "interstitial"
	CreateAuctionConfigurationV2JSONBodyAdTypeRewarded     CreateAuctionConfigurationV2JSONBodyAdType = "rewarded"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyBidding.
const (
	CreateAuctionConfigurationV2JSONBodyBiddingAdmob      CreateAuctionConfigurationV2JSONBodyBidding = "admob"
	CreateAuctionConfigurationV2JSONBodyBiddingAmazon     CreateAuctionConfigurationV2JSONBodyBidding = "amazon"
	CreateAuctionConfigurationV2JSONBodyBiddingApplovin   CreateAuctionConfigurationV2JSONBodyBidding = "applovin"
	CreateAuctionConfigurationV2JSONBodyBiddingBidmachine CreateAuctionConfigurationV2JSONBodyBidding = "bidmachine"
	CreateAuctionConfigurationV2JSONBodyBiddingBigoads    CreateAuctionConfigurationV2JSONBodyBidding = "bigoads"
	CreateAuctionConfigurationV2JSONBodyBiddingChartboost CreateAuctionConfigurationV2JSONBodyBidding = "chartboost"
	CreateAuctionConfigurationV2JSONBodyBiddingDtexchange CreateAuctionConfigurationV2JSONBodyBidding = "dtexchange"
	CreateAuctionConfigurationV2JSONBodyBiddingGam        CreateAuctionConfigurationV2JSONBodyBidding = "gam"
	CreateAuctionConfigurationV2JSONBodyBiddingInmobi     CreateAuctionConfigurationV2JSONBodyBidding = "inmobi"
	CreateAuctionConfigurationV2JSONBodyBiddingIronsource CreateAuctionConfigurationV2JSONBodyBidding = "ironsource"
	CreateAuctionConfigurationV2JSONBodyBiddingMeta       CreateAuctionConfigurationV2JSONBodyBidding = "meta"
	CreateAuctionConfigurationV2JSONBodyBiddingMintegral  CreateAuctionConfigurationV2JSONBodyBidding = "mintegral"
	CreateAuctionConfigurationV2JSONBodyBiddingMobilefuse CreateAuctionConfigurationV2JSONBodyBidding = "mobilefuse"
	CreateAuctionConfigurationV2JSONBodyBiddingUnityads   CreateAuctionConfigurationV2JSONBodyBidding = "unityads"
	CreateAuctionConfigurationV2JSONBodyBiddingVkads      CreateAuctionConfigurationV2JSONBodyBidding = "vkads"
	CreateAuctionConfigurationV2JSONBodyBiddingVungle     CreateAuctionConfigurationV2JSONBodyBidding = "vungle"
	CreateAuctionConfigurationV2JSONBodyBiddingYandex     CreateAuctionConfigurationV2JSONBodyBidding = "yandex"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyDemands.
const (
	CreateAuctionConfigurationV2JSONBodyDemandsAdmob      CreateAuctionConfigurationV2JSONBodyDemands = "admob"
	CreateAuctionConfigurationV2JSONBodyDemandsAmazon     CreateAuctionConfigurationV2JSONBodyDemands = "amazon"
	CreateAuctionConfigurationV2JSONBodyDemandsApplovin   CreateAuctionConfigurationV2JSONBodyDemands = "applovin"
	CreateAuctionConfigurationV2JSONBodyDemandsBidmachine CreateAuctionConfigurationV2JSONBodyDemands = "bidmachine"
	CreateAuctionConfigurationV2JSONBodyDemandsBigoads    CreateAuctionConfigurationV2JSONBodyDemands = "bigoads"
	CreateAuctionConfigurationV2JSONBodyDemandsChartboost CreateAuctionConfigurationV2JSONBodyDemands = "chartboost"
	CreateAuctionConfigurationV2JSONBodyDemandsDtexchange CreateAuctionConfigurationV2JSONBodyDemands = "dtexchange"
	CreateAuctionConfigurationV2JSONBodyDemandsGam        CreateAuctionConfigurationV2JSONBodyDemands = "gam"
	CreateAuctionConfigurationV2JSONBodyDemandsInmobi     CreateAuctionConfigurationV2JSONBodyDemands = "inmobi"
	CreateAuctionConfigurationV2JSONBodyDemandsIronsource CreateAuctionConfigurationV2JSONBodyDemands = "ironsource"
	CreateAuctionConfigurationV2JSONBodyDemandsMeta       CreateAuctionConfigurationV2JSONBodyDemands = "meta"
	CreateAuctionConfigurationV2JSONBodyDemandsMintegral  CreateAuctionConfigurationV2JSONBodyDemands = "mintegral"
	CreateAuctionConfigurationV2JSONBodyDemandsMobilefuse CreateAuctionConfigurationV2JSONBodyDemands = "mobilefuse"
	CreateAuctionConfigurationV2JSONBodyDemandsUnityads   CreateAuctionConfigurationV2JSONBodyDemands = "unityads"
	CreateAuctionConfigurationV2JSONBodyDemandsVkads      CreateAuctionConfigurationV2JSONBodyDemands = "vkads"
	CreateAuctionConfigurationV2JSONBodyDemandsVungle     CreateAuctionConfigurationV2JSONBodyDemands = "vungle"
	CreateAuctionConfigurationV2JSONBodyDemandsYandex     CreateAuctionConfigurationV2JSONBodyDemands = "yandex"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyAdType.
const (
	UpdateAuctionConfigurationV2JSONBodyAdTypeBanner       UpdateAuctionConfigurationV2JSONBodyAdType = "banner"
	UpdateAuctionConfigurationV2JSONBodyAdTypeInterstitial UpdateAuctionConfigurationV2JSONBodyAdType = "interstitial"
	UpdateAuctionConfigurationV2JSONBodyAdTypeRewarded     UpdateAuctionConfigurationV2JSONBodyAdType = "rewarded"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyBidding.
const (
	UpdateAuctionConfigurationV2JSONBodyBiddingAdmob      UpdateAuctionConfigurationV2JSONBodyBidding = "admob"
	UpdateAuctionConfigurationV2JSONBodyBiddingAmazon     UpdateAuctionConfigurationV2JSONBodyBidding = "amazon"
	UpdateAuctionConfigurationV2JSONBodyBiddingApplovin   UpdateAuctionConfigurationV2JSONBodyBidding = "applovin"
	UpdateAuctionConfigurationV2JSONBodyBiddingBidmachine UpdateAuctionConfigurationV2JSONBodyBidding = "bidmachine"
	UpdateAuctionConfigurationV2JSONBodyBiddingBigoads    UpdateAuctionConfigurationV2JSONBodyBidding = "bigoads"
	UpdateAuctionConfigurationV2JSONBodyBiddingChartboost UpdateAuctionConfigurationV2JSONBodyBidding = "chartboost"
	UpdateAuctionConfigurationV2JSONBodyBiddingDtexchange UpdateAuctionConfigurationV2JSONBodyBidding = "dtexchange"
	UpdateAuctionConfigurationV2JSONBodyBiddingGam        UpdateAuctionConfigurationV2JSONBodyBidding = "gam"
	UpdateAuctionConfigurationV2JSONBodyBiddingInmobi     UpdateAuctionConfigurationV2JSONBodyBidding = "inmobi"
	UpdateAuctionConfigurationV2JSONBodyBiddingIronsource UpdateAuctionConfigurationV2JSONBodyBidding = "ironsource"
	UpdateAuctionConfigurationV2JSONBodyBiddingMeta       UpdateAuctionConfigurationV2JSONBodyBidding = "meta"
	UpdateAuctionConfigurationV2JSONBodyBiddingMintegral  UpdateAuctionConfigurationV2JSONBodyBidding = "mintegral"
	UpdateAuctionConfigurationV2JSONBodyBiddingMobilefuse UpdateAuctionConfigurationV2JSONBodyBidding = "mobilefuse"
	UpdateAuctionConfigurationV2JSONBodyBiddingUnityads   UpdateAuctionConfigurationV2JSONBodyBidding = "unityads"
	UpdateAuctionConfigurationV2JSONBodyBiddingVkads      UpdateAuctionConfigurationV2JSONBodyBidding = "vkads"
	UpdateAuctionConfigurationV2JSONBodyBiddingVungle     UpdateAuctionConfigurationV2JSONBodyBidding = "vungle"
	UpdateAuctionConfigurationV2JSONBodyBiddingYandex     UpdateAuctionConfigurationV2JSONBodyBidding = "yandex"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyDemands.
const (
	UpdateAuctionConfigurationV2JSONBodyDemandsAdmob      UpdateAuctionConfigurationV2JSONBodyDemands = "admob"
	UpdateAuctionConfigurationV2JSONBodyDemandsAmazon     UpdateAuctionConfigurationV2JSONBodyDemands = "amazon"
	UpdateAuctionConfigurationV2JSONBodyDemandsApplovin   UpdateAuctionConfigurationV2JSONBodyDemands = "applovin"
	UpdateAuctionConfigurationV2JSONBodyDemandsBidmachine UpdateAuctionConfigurationV2JSONBodyDemands = "bidmachine"
	UpdateAuctionConfigurationV2JSONBodyDemandsBigoads    UpdateAuctionConfigurationV2JSONBodyDemands = "bigoads"
	UpdateAuctionConfigurationV2JSONBodyDemandsChartboost UpdateAuctionConfigurationV2JSONBodyDemands = "chartboost"
	UpdateAuctionConfigurationV2JSONBodyDemandsDtexchange UpdateAuctionConfigurationV2JSONBodyDemands = "dtexchange"
	UpdateAuctionConfigurationV2JSONBodyDemandsGam        UpdateAuctionConfigurationV2JSONBodyDemands = "gam"
	UpdateAuctionConfigurationV2JSONBodyDemandsInmobi     UpdateAuctionConfigurationV2JSONBodyDemands = "inmobi"
	UpdateAuctionConfigurationV2JSONBodyDemandsIronsource UpdateAuctionConfigurationV2JSONBodyDemands = "ironsource"
	UpdateAuctionConfigurationV2JSONBodyDemandsMeta       UpdateAuctionConfigurationV2JSONBodyDemands = "meta"
	UpdateAuctionConfigurationV2JSONBodyDemandsMintegral  UpdateAuctionConfigurationV2JSONBodyDemands = "mintegral"
	UpdateAuctionConfigurationV2JSONBodyDemandsMobilefuse UpdateAuctionConfigurationV2JSONBodyDemands = "mobilefuse"
	UpdateAuctionConfigurationV2JSONBodyDemandsUnityads   UpdateAuctionConfigurationV2JSONBodyDemands = "unityads"
	UpdateAuctionConfigurationV2JSONBodyDemandsVkads      UpdateAuctionConfigurationV2JSONBodyDemands = "vkads"
	UpdateAuctionConfigurationV2JSONBodyDemandsVungle     UpdateAuctionConfigurationV2JSONBodyDemands = "vungle"
	UpdateAuctionConfigurationV2JSONBodyDemandsYandex     UpdateAuctionConfigurationV2JSONBodyDemands = "yandex"
)

// IdParam A positive integer ID
type IdParam = int

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Error code
		Code int `json:"code"`

		// Message Error message
		Message string `json:"message"`
	} `json:"error"`
}

// CreateAppDemandProfileJSONBody defines parameters for CreateAppDemandProfile.
type CreateAppDemandProfileJSONBody struct {
	// AccountId A positive integer ID
	AccountId int `json:"account_id"`

	// AccountType The type of account associated with this demand profile
	AccountType string `json:"account_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Data Additional data associated with the demand profile
	Data map[string]interface{} `json:"data"`

	// DemandSourceId A positive integer ID
	DemandSourceId int `json:"demand_source_id"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// UpdateAppDemandProfileJSONBody defines parameters for UpdateAppDemandProfile.
type UpdateAppDemandProfileJSONBody struct {
	// AccountId A positive integer ID
	AccountId *int `json:"account_id,omitempty"`

	// AccountType The type of account associated with this demand profile
	AccountType *string `json:"account_type,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Data Additional data associated with the demand profile
	Data *map[string]interface{} `json:"data,omitempty"`

	// DemandSourceId A positive integer ID
	DemandSourceId *int `json:"demand_source_id,omitempty"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// CreateAppJSONBody defines parameters for CreateApp.
type CreateAppJSONBody struct {
	// AppKey A unique key for the app
	AppKey string `json:"app_key"`

	// HumanName The human-readable name of the app
	HumanName string `json:"human_name"`

	// Id A positive integer ID
	Id int `json:"id"`

	// PackageName The package name of the app
	PackageName string                      `json:"package_name"`
	PlatformId  CreateAppJSONBodyPlatformId `json:"platform_id"`
	PublicUid   *openapi_types.UUID         `json:"public_uid,omitempty"`

	// UserId A positive integer ID
	UserId int `json:"user_id"`
}

// CreateAppJSONBodyPlatformId defines parameters for CreateApp.
type CreateAppJSONBodyPlatformId string

// UpdateAppJSONBody defines parameters for UpdateApp.
type UpdateAppJSONBody struct {
	// AppKey A unique key for the app
	AppKey *string `json:"app_key,omitempty"`

	// HumanName The human-readable name of the app
	HumanName *string `json:"human_name,omitempty"`

	// Id A positive integer ID
	Id *int `json:"id,omitempty"`

	// PackageName The package name of the app
	PackageName *string                      `json:"package_name,omitempty"`
	PlatformId  *UpdateAppJSONBodyPlatformId `json:"platform_id,omitempty"`
	PublicUid   *openapi_types.UUID          `json:"public_uid,omitempty"`

	// UserId A positive integer ID
	UserId *int `json:"user_id,omitempty"`
}

// UpdateAppJSONBodyPlatformId defines parameters for UpdateApp.
type UpdateAppJSONBodyPlatformId string

// CreateAuctionConfigurationJSONBody defines parameters for CreateAuctionConfiguration.
type CreateAuctionConfigurationJSONBody struct {
	AdType CreateAuctionConfigurationJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name Name of the auction configuration
	Name string `json:"name"`

	// Pricefloor Price floor for the auction configuration
	Pricefloor float32             `json:"pricefloor"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// Rounds Auction rounds
	Rounds []struct {
		// Demands List of demands for the round
		Demands []string `json:"demands"`

		// Id Round ID
		Id string `json:"id"`

		// Timeout Timeout for the round in milliseconds
		Timeout int `json:"timeout"`
	} `json:"rounds"`
}

// CreateAuctionConfigurationJSONBodyAdType defines parameters for CreateAuctionConfiguration.
type CreateAuctionConfigurationJSONBodyAdType string

// UpdateAuctionConfigurationJSONBody defines parameters for UpdateAuctionConfiguration.
type UpdateAuctionConfigurationJSONBody struct {
	AdType UpdateAuctionConfigurationJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name Name of the auction configuration
	Name string `json:"name"`

	// Pricefloor Price floor for the auction configuration
	Pricefloor float32             `json:"pricefloor"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// Rounds Auction rounds
	Rounds []struct {
		// Demands List of demands for the round
		Demands []string `json:"demands"`

		// Id Round ID
		Id string `json:"id"`

		// Timeout Timeout for the round in milliseconds
		Timeout int `json:"timeout"`
	} `json:"rounds"`
}

// UpdateAuctionConfigurationJSONBodyAdType defines parameters for UpdateAuctionConfiguration.
type UpdateAuctionConfigurationJSONBodyAdType string

// CreateCountryJSONBody defines parameters for CreateCountry.
type CreateCountryJSONBody struct {
	// Alpha2Code The ISO 3166-1 alpha-2 code for the country
	Alpha2Code string `json:"alpha_2_code"`

	// Alpha3Code The ISO 3166-1 alpha-3 code for the country
	Alpha3Code string `json:"alpha_3_code"`

	// HumanName The human-readable name of the country
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// UpdateCountryJSONBody defines parameters for UpdateCountry.
type UpdateCountryJSONBody struct {
	// Alpha2Code The ISO 3166-1 alpha-2 code for the country
	Alpha2Code *string `json:"alpha_2_code,omitempty"`

	// Alpha3Code The ISO 3166-1 alpha-3 code for the country
	Alpha3Code *string `json:"alpha_3_code,omitempty"`

	// HumanName The human-readable name of the country
	HumanName *string `json:"human_name,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// CreateDemandSourceAccountJSONBody defines parameters for CreateDemandSourceAccount.
type CreateDemandSourceAccountJSONBody struct {
	// DemandSourceId A positive integer ID
	DemandSourceId int `json:"demand_source_id"`

	// Extra Additional information for the demand source account
	Extra map[string]interface{} `json:"extra"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsBidding Indicates whether bidding is enabled for this demand source account
	IsBidding bool               `json:"is_bidding"`
	PublicUid openapi_types.UUID `json:"public_uid"`

	// Type The type of the demand source account
	Type string `json:"type"`

	// UserId A positive integer ID
	UserId int `json:"user_id"`
}

// UpdateDemandSourceAccountJSONBody defines parameters for UpdateDemandSourceAccount.
type UpdateDemandSourceAccountJSONBody struct {
	// DemandSourceId A positive integer ID
	DemandSourceId *int `json:"demand_source_id,omitempty"`

	// Extra Additional information for the demand source account
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsBidding Indicates whether bidding is enabled for this demand source account
	IsBidding *bool               `json:"is_bidding,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`

	// Type The type of the demand source account
	Type *string `json:"type,omitempty"`

	// UserId A positive integer ID
	UserId *int `json:"user_id,omitempty"`
}

// CreateDemandSourceJSONBody defines parameters for CreateDemandSource.
type CreateDemandSourceJSONBody struct {
	// ApiKey The API key associated with the demand source
	ApiKey string `json:"api_key"`

	// HumanName The human-readable name of the demand source
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// UpdateDemandSourceJSONBody defines parameters for UpdateDemandSource.
type UpdateDemandSourceJSONBody struct {
	// ApiKey The API key associated with the demand source
	ApiKey string `json:"api_key"`

	// HumanName The human-readable name of the demand source
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// CreateSegmentJSONBody defines parameters for CreateSegment.
type CreateSegmentJSONBody struct {
	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Description The description of the segment
	Description string `json:"description"`

	// Enabled Indicates if the segment is enabled
	Enabled bool `json:"enabled"`

	// Filters Filters applied to the segment
	Filters []struct {
		// Name The name of the filter
		Name string `json:"name"`

		// Operator The operator used in the filter
		Operator string `json:"operator"`

		// Type The type of filter
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"filters"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name The name of the segment
	Name      string             `json:"name"`
	PublicUid openapi_types.UUID `json:"public_uid"`
}

// UpdateSegmentJSONBody defines parameters for UpdateSegment.
type UpdateSegmentJSONBody struct {
	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Description The description of the segment
	Description string `json:"description"`

	// Enabled Indicates if the segment is enabled
	Enabled bool `json:"enabled"`

	// Filters Filters applied to the segment
	Filters []struct {
		// Name The name of the filter
		Name string `json:"name"`

		// Operator The operator used in the filter
		Operator string `json:"operator"`

		// Type The type of filter
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"filters"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name The name of the segment
	Name      string              `json:"name"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	Email openapi_types.Email `json:"email"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// CreateAuctionConfigurationV2JSONBody defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBody struct {
	AdType CreateAuctionConfigurationV2JSONBodyAdType `json:"ad_type"`

	// AdUnitIds List of ad unit IDs
	AdUnitIds *[]int `json:"ad_unit_ids,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Bidding List of bidding sources
	Bidding *[]CreateAuctionConfigurationV2JSONBodyBidding `json:"bidding,omitempty"`

	// Demands List of demand sources
	Demands *[]CreateAuctionConfigurationV2JSONBodyDemands `json:"demands,omitempty"`

	// ExternalWinNotifications Whether external win notifications are enabled
	ExternalWinNotifications *bool `json:"external_win_notifications,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsDefault Indicates if this is the default configuration
	IsDefault  *bool               `json:"is_default,omitempty"`
	Name       string              `json:"name"`
	Pricefloor float32             `json:"pricefloor"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// SegmentId A positive integer ID
	SegmentId *int `json:"segment_id,omitempty"`

	// Settings A map of configuration settings
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// Timeout Timeout value in milliseconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// CreateAuctionConfigurationV2JSONBodyAdType defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyAdType string

// CreateAuctionConfigurationV2JSONBodyBidding defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyBidding string

// CreateAuctionConfigurationV2JSONBodyDemands defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyDemands string

// UpdateAuctionConfigurationV2JSONBody defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBody struct {
	AdType *UpdateAuctionConfigurationV2JSONBodyAdType `json:"ad_type,omitempty"`

	// AdUnitIds List of ad unit IDs
	AdUnitIds *[]int `json:"ad_unit_ids,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Bidding List of bidding sources
	Bidding *[]UpdateAuctionConfigurationV2JSONBodyBidding `json:"bidding,omitempty"`

	// Demands List of demand sources
	Demands *[]UpdateAuctionConfigurationV2JSONBodyDemands `json:"demands,omitempty"`

	// ExternalWinNotifications Whether external win notifications are enabled
	ExternalWinNotifications *bool `json:"external_win_notifications,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsDefault Indicates if this is the default configuration
	IsDefault  *bool               `json:"is_default,omitempty"`
	Name       *string             `json:"name,omitempty"`
	Pricefloor *float32            `json:"pricefloor,omitempty"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// SegmentId A positive integer ID
	SegmentId *int `json:"segment_id,omitempty"`

	// Settings A map of configuration settings
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// Timeout Timeout value in milliseconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// UpdateAuctionConfigurationV2JSONBodyAdType defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyAdType string

// UpdateAuctionConfigurationV2JSONBodyBidding defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyBidding string

// UpdateAuctionConfigurationV2JSONBodyDemands defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyDemands string

// CreateAppDemandProfileJSONRequestBody defines body for CreateAppDemandProfile for application/json ContentType.
type CreateAppDemandProfileJSONRequestBody CreateAppDemandProfileJSONBody

// UpdateAppDemandProfileJSONRequestBody defines body for UpdateAppDemandProfile for application/json ContentType.
type UpdateAppDemandProfileJSONRequestBody UpdateAppDemandProfileJSONBody

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody CreateAppJSONBody

// UpdateAppJSONRequestBody defines body for UpdateApp for application/json ContentType.
type UpdateAppJSONRequestBody UpdateAppJSONBody

// CreateAuctionConfigurationJSONRequestBody defines body for CreateAuctionConfiguration for application/json ContentType.
type CreateAuctionConfigurationJSONRequestBody CreateAuctionConfigurationJSONBody

// UpdateAuctionConfigurationJSONRequestBody defines body for UpdateAuctionConfiguration for application/json ContentType.
type UpdateAuctionConfigurationJSONRequestBody UpdateAuctionConfigurationJSONBody

// CreateCountryJSONRequestBody defines body for CreateCountry for application/json ContentType.
type CreateCountryJSONRequestBody CreateCountryJSONBody

// UpdateCountryJSONRequestBody defines body for UpdateCountry for application/json ContentType.
type UpdateCountryJSONRequestBody UpdateCountryJSONBody

// CreateDemandSourceAccountJSONRequestBody defines body for CreateDemandSourceAccount for application/json ContentType.
type CreateDemandSourceAccountJSONRequestBody CreateDemandSourceAccountJSONBody

// UpdateDemandSourceAccountJSONRequestBody defines body for UpdateDemandSourceAccount for application/json ContentType.
type UpdateDemandSourceAccountJSONRequestBody UpdateDemandSourceAccountJSONBody

// CreateDemandSourceJSONRequestBody defines body for CreateDemandSource for application/json ContentType.
type CreateDemandSourceJSONRequestBody CreateDemandSourceJSONBody

// UpdateDemandSourceJSONRequestBody defines body for UpdateDemandSource for application/json ContentType.
type UpdateDemandSourceJSONRequestBody UpdateDemandSourceJSONBody

// CreateSegmentJSONRequestBody defines body for CreateSegment for application/json ContentType.
type CreateSegmentJSONRequestBody CreateSegmentJSONBody

// UpdateSegmentJSONRequestBody defines body for UpdateSegment for application/json ContentType.
type UpdateSegmentJSONRequestBody UpdateSegmentJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// CreateAuctionConfigurationV2JSONRequestBody defines body for CreateAuctionConfigurationV2 for application/json ContentType.
type CreateAuctionConfigurationV2JSONRequestBody CreateAuctionConfigurationV2JSONBody

// UpdateAuctionConfigurationV2JSONRequestBody defines body for UpdateAuctionConfigurationV2 for application/json ContentType.
type UpdateAuctionConfigurationV2JSONRequestBody UpdateAuctionConfigurationV2JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List app demand profiles
	// (GET /app_demand_profiles)
	GetAppDemandProfiles(ctx echo.Context) error
	// Create app demand profile
	// (POST /app_demand_profiles)
	CreateAppDemandProfile(ctx echo.Context) error
	// Delete app demand profile
	// (DELETE /app_demand_profiles/{id})
	DeleteAppDemandProfile(ctx echo.Context, id IdParam) error
	// Get app demand profile
	// (GET /app_demand_profiles/{id})
	GetAppDemandProfile(ctx echo.Context, id IdParam) error
	// Update app demand profile
	// (PATCH /app_demand_profiles/{id})
	UpdateAppDemandProfile(ctx echo.Context, id IdParam) error
	// List apps
	// (GET /apps)
	GetApps(ctx echo.Context) error
	// Create app
	// (POST /apps)
	CreateApp(ctx echo.Context) error
	// Delete app
	// (DELETE /apps/{id})
	DeleteApp(ctx echo.Context, id IdParam) error
	// Get app
	// (GET /apps/{id})
	GetApp(ctx echo.Context, id IdParam) error
	// Update app
	// (PATCH /apps/{id})
	UpdateApp(ctx echo.Context, id IdParam) error
	// List auction configurations
	// (GET /auction_configurations)
	GetAuctionConfigurations(ctx echo.Context) error
	// Create auction configuration
	// (POST /auction_configurations)
	CreateAuctionConfiguration(ctx echo.Context) error
	// Delete auction configuration
	// (DELETE /auction_configurations/{id})
	DeleteAuctionConfiguration(ctx echo.Context, id IdParam) error
	// Get auction configuration
	// (GET /auction_configurations/{id})
	GetAuctionConfiguration(ctx echo.Context, id IdParam) error
	// Update auction configuration
	// (PATCH /auction_configurations/{id})
	UpdateAuctionConfiguration(ctx echo.Context, id IdParam) error
	// List countries
	// (GET /countries)
	GetCountries(ctx echo.Context) error
	// Create country
	// (POST /countries)
	CreateCountry(ctx echo.Context) error
	// Delete country
	// (DELETE /countries/{id})
	DeleteCountry(ctx echo.Context, id IdParam) error
	// Get country
	// (GET /countries/{id})
	GetCountry(ctx echo.Context, id IdParam) error
	// Update country
	// (PATCH /countries/{id})
	UpdateCountry(ctx echo.Context, id IdParam) error
	// List demand source accounts
	// (GET /demand_source_accounts)
	GetDemandSourceAccounts(ctx echo.Context) error
	// Create demand source account
	// (POST /demand_source_accounts)
	CreateDemandSourceAccount(ctx echo.Context) error
	// Delete demand source account
	// (DELETE /demand_source_accounts/{id})
	DeleteDemandSourceAccount(ctx echo.Context, id IdParam) error
	// Get demand source account
	// (GET /demand_source_accounts/{id})
	GetDemandSourceAccount(ctx echo.Context, id IdParam) error
	// Update demand source account
	// (PATCH /demand_source_accounts/{id})
	UpdateDemandSourceAccount(ctx echo.Context, id IdParam) error
	// List demand sources
	// (GET /demand_sources)
	GetDemandSources(ctx echo.Context) error
	// Create demand source
	// (POST /demand_sources)
	CreateDemandSource(ctx echo.Context) error
	// Delete demand source
	// (DELETE /demand_sources/{id})
	DeleteDemandSource(ctx echo.Context, id IdParam) error
	// Get demand source
	// (GET /demand_sources/{id})
	GetDemandSource(ctx echo.Context, id IdParam) error
	// Update demand source
	// (PATCH /demand_sources/{id})
	UpdateDemandSource(ctx echo.Context, id IdParam) error
	// List segments
	// (GET /segments)
	GetSegments(ctx echo.Context) error
	// Create segment
	// (POST /segments)
	CreateSegment(ctx echo.Context) error
	// Delete segment
	// (DELETE /segments/{id})
	DeleteSegment(ctx echo.Context, id IdParam) error
	// Get segment
	// (GET /segments/{id})
	GetSegment(ctx echo.Context, id IdParam) error
	// Update segment
	// (PATCH /segments/{id})
	UpdateSegment(ctx echo.Context, id IdParam) error
	// List users
	// (GET /users)
	GetUsers(ctx echo.Context) error
	// Create user
	// (POST /users)
	CreateUser(ctx echo.Context) error
	// Get current user
	// (GET /users/me)
	GetCurrentUser(ctx echo.Context) error
	// Delete user
	// (DELETE /users/{id})
	DeleteUser(ctx echo.Context, id IdParam) error
	// Get user
	// (GET /users/{id})
	GetUser(ctx echo.Context, id IdParam) error
	// Update user
	// (PATCH /users/{id})
	UpdateUser(ctx echo.Context, id IdParam) error
	// List auction configurations V2
	// (GET /v2/auction_configurations)
	GetAuctionConfigurationsV2(ctx echo.Context) error
	// Create auction configuration V2
	// (POST /v2/auction_configurations)
	CreateAuctionConfigurationV2(ctx echo.Context) error
	// Delete auction configuration
	// (DELETE /v2/auction_configurations/{id})
	DeleteAuctionConfigurationV2(ctx echo.Context, id IdParam) error
	// Get auction configuration V2
	// (GET /v2/auction_configurations/{id})
	GetAuctionConfigurationV2(ctx echo.Context, id IdParam) error
	// Update auction configuration V2
	// (PATCH /v2/auction_configurations/{id})
	UpdateAuctionConfigurationV2(ctx echo.Context, id IdParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAppDemandProfiles converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppDemandProfiles(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAppDemandProfiles(ctx)
	return err
}

// CreateAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAppDemandProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAppDemandProfile(ctx)
	return err
}

// DeleteAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAppDemandProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAppDemandProfile(ctx, id)
	return err
}

// GetAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppDemandProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAppDemandProfile(ctx, id)
	return err
}

// UpdateAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAppDemandProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAppDemandProfile(ctx, id)
	return err
}

// GetApps converts echo context to params.
func (w *ServerInterfaceWrapper) GetApps(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApps(ctx)
	return err
}

// CreateApp converts echo context to params.
func (w *ServerInterfaceWrapper) CreateApp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateApp(ctx)
	return err
}

// DeleteApp converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApp(ctx, id)
	return err
}

// GetApp converts echo context to params.
func (w *ServerInterfaceWrapper) GetApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApp(ctx, id)
	return err
}

// UpdateApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateApp(ctx, id)
	return err
}

// GetAuctionConfigurations converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurations(ctx)
	return err
}

// CreateAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuctionConfiguration(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuctionConfiguration(ctx)
	return err
}

// DeleteAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuctionConfiguration(ctx, id)
	return err
}

// GetAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfiguration(ctx, id)
	return err
}

// UpdateAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuctionConfiguration(ctx, id)
	return err
}

// GetCountries converts echo context to params.
func (w *ServerInterfaceWrapper) GetCountries(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCountries(ctx)
	return err
}

// CreateCountry converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCountry(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCountry(ctx)
	return err
}

// DeleteCountry converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCountry(ctx, id)
	return err
}

// GetCountry converts echo context to params.
func (w *ServerInterfaceWrapper) GetCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCountry(ctx, id)
	return err
}

// UpdateCountry converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCountry(ctx, id)
	return err
}

// GetDemandSourceAccounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSourceAccounts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSourceAccounts(ctx)
	return err
}

// CreateDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDemandSourceAccount(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDemandSourceAccount(ctx)
	return err
}

// DeleteDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDemandSourceAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDemandSourceAccount(ctx, id)
	return err
}

// GetDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSourceAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSourceAccount(ctx, id)
	return err
}

// UpdateDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDemandSourceAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDemandSourceAccount(ctx, id)
	return err
}

// GetDemandSources converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSources(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSources(ctx)
	return err
}

// CreateDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDemandSource(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDemandSource(ctx)
	return err
}

// DeleteDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDemandSource(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDemandSource(ctx, id)
	return err
}

// GetDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSource(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSource(ctx, id)
	return err
}

// UpdateDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDemandSource(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDemandSource(ctx, id)
	return err
}

// GetSegments converts echo context to params.
func (w *ServerInterfaceWrapper) GetSegments(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSegments(ctx)
	return err
}

// CreateSegment converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSegment(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSegment(ctx)
	return err
}

// DeleteSegment converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSegment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSegment(ctx, id)
	return err
}

// GetSegment converts echo context to params.
func (w *ServerInterfaceWrapper) GetSegment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSegment(ctx, id)
	return err
}

// UpdateSegment converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSegment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSegment(ctx, id)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// GetAuctionConfigurationsV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurationsV2(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurationsV2(ctx)
	return err
}

// CreateAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuctionConfigurationV2(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuctionConfigurationV2(ctx)
	return err
}

// DeleteAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuctionConfigurationV2(ctx, id)
	return err
}

// GetAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurationV2(ctx, id)
	return err
}

// UpdateAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuctionConfigurationV2(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/app_demand_profiles", wrapper.GetAppDemandProfiles)
	router.POST(baseURL+"/app_demand_profiles", wrapper.CreateAppDemandProfile)
	router.DELETE(baseURL+"/app_demand_profiles/:id", wrapper.DeleteAppDemandProfile)
	router.GET(baseURL+"/app_demand_profiles/:id", wrapper.GetAppDemandProfile)
	router.PATCH(baseURL+"/app_demand_profiles/:id", wrapper.UpdateAppDemandProfile)
	router.GET(baseURL+"/apps", wrapper.GetApps)
	router.POST(baseURL+"/apps", wrapper.CreateApp)
	router.DELETE(baseURL+"/apps/:id", wrapper.DeleteApp)
	router.GET(baseURL+"/apps/:id", wrapper.GetApp)
	router.PATCH(baseURL+"/apps/:id", wrapper.UpdateApp)
	router.GET(baseURL+"/auction_configurations", wrapper.GetAuctionConfigurations)
	router.POST(baseURL+"/auction_configurations", wrapper.CreateAuctionConfiguration)
	router.DELETE(baseURL+"/auction_configurations/:id", wrapper.DeleteAuctionConfiguration)
	router.GET(baseURL+"/auction_configurations/:id", wrapper.GetAuctionConfiguration)
	router.PATCH(baseURL+"/auction_configurations/:id", wrapper.UpdateAuctionConfiguration)
	router.GET(baseURL+"/countries", wrapper.GetCountries)
	router.POST(baseURL+"/countries", wrapper.CreateCountry)
	router.DELETE(baseURL+"/countries/:id", wrapper.DeleteCountry)
	router.GET(baseURL+"/countries/:id", wrapper.GetCountry)
	router.PATCH(baseURL+"/countries/:id", wrapper.UpdateCountry)
	router.GET(baseURL+"/demand_source_accounts", wrapper.GetDemandSourceAccounts)
	router.POST(baseURL+"/demand_source_accounts", wrapper.CreateDemandSourceAccount)
	router.DELETE(baseURL+"/demand_source_accounts/:id", wrapper.DeleteDemandSourceAccount)
	router.GET(baseURL+"/demand_source_accounts/:id", wrapper.GetDemandSourceAccount)
	router.PATCH(baseURL+"/demand_source_accounts/:id", wrapper.UpdateDemandSourceAccount)
	router.GET(baseURL+"/demand_sources", wrapper.GetDemandSources)
	router.POST(baseURL+"/demand_sources", wrapper.CreateDemandSource)
	router.DELETE(baseURL+"/demand_sources/:id", wrapper.DeleteDemandSource)
	router.GET(baseURL+"/demand_sources/:id", wrapper.GetDemandSource)
	router.PATCH(baseURL+"/demand_sources/:id", wrapper.UpdateDemandSource)
	router.GET(baseURL+"/segments", wrapper.GetSegments)
	router.POST(baseURL+"/segments", wrapper.CreateSegment)
	router.DELETE(baseURL+"/segments/:id", wrapper.DeleteSegment)
	router.GET(baseURL+"/segments/:id", wrapper.GetSegment)
	router.PATCH(baseURL+"/segments/:id", wrapper.UpdateSegment)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.POST(baseURL+"/users", wrapper.CreateUser)
	router.GET(baseURL+"/users/me", wrapper.GetCurrentUser)
	router.DELETE(baseURL+"/users/:id", wrapper.DeleteUser)
	router.GET(baseURL+"/users/:id", wrapper.GetUser)
	router.PATCH(baseURL+"/users/:id", wrapper.UpdateUser)
	router.GET(baseURL+"/v2/auction_configurations", wrapper.GetAuctionConfigurationsV2)
	router.POST(baseURL+"/v2/auction_configurations", wrapper.CreateAuctionConfigurationV2)
	router.DELETE(baseURL+"/v2/auction_configurations/:id", wrapper.DeleteAuctionConfigurationV2)
	router.GET(baseURL+"/v2/auction_configurations/:id", wrapper.GetAuctionConfigurationV2)
	router.PATCH(baseURL+"/v2/auction_configurations/:id", wrapper.UpdateAuctionConfigurationV2)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RcXW/juNX+KwTfuXgL2HHiFHvhu3TSLoJuO8Fmp70YDAxGom3uSJSWpJJxA//34pDU",
	"N/VhW5Kz3atYEkUePufjOSIP84a9KIwjTrmSePWGYyJISBUV+or5j3ANP30qPcFixSKOV/iOI+ajaIMI",
	"ElRGifAonmEGj2KidniGOQkpXmHm4xkW9LeECerjlRIJnWHp7WhIoNcPgm7wCv/fIpdiYZ7KBfPx4XCA",
	"t2UccUm1RH8VIhI/2ztww4u4olzBTxLHAfMIiLj4VYKcbz2HotCrGa02T/0MRZ6XCEH9KwyN7Ht6UH+u",
	"9rEW5QPz8Sq9cWXaXGlBZvhDKgjeKRXL1UJLOLeNIrFd+IJs1GJ5vbye3yytZHiGKU9CvPqCnwnnVGiQ",
	"QTuKKUYCje0rET718dcZVkwFAPqdj34BmWbYiIalEoxv8WGGiU9iRcX8G90XRc5uDiV2HUaehEjQWFBJ",
	"uWJ8i+yo6BvdS7SJBHohgkWJRMRHnKrXSHyTBQCIH0bPeIZJSP6jZQN1Ry8Mfj4zPyTejnGqL7YR8eFV",
	"b0eEeo4iqUAiRb97O8K30GZLQg1lGD0z+CEinllxSBXMIASgt0KDDM0CukkkPE84U3szwMs3+zfh2wCe",
	"7Qn36feyLvQs/073TnXEcUENcTwU/CQIPm3w6ku72ZM4nsciiiU+zN4KXvrFuG0cELWJRLjWV7skJHyt",
	"3XqGY+J9I1uaXiaSCtOKxPEabOvroYhBHNvJzn0aEu7DqBsW0NLcK8+mh6I8fhsyMEv9w7yyNrZjEfC8",
	"KOGqfKGMO/pEEW0cxg6i51+pp3AFqnvd56NFyInb3KeKsAAkagYwa3RpJDWGgCYVipkwbnHpisu2HwPv",
	"PH3pUMH9qF7gbTDXrpfAMyHU91fVfaoTt8qMObXpS7cYSllOvMEoe7BuxW5r7P/LjiJ4ohMA0xIRKSOP",
	"EUV99MrUDqkdk8hMEKV2oIPqT5Rv1Q6vbtzhsLeI2pfqiYnvM/hJAgQNHGLRulQVHTvcupdE3e1iwUIi",
	"9nPTPk6eA+atkx7v6ZbzRKdEzRb4qE3MMR9jbO6QcaEY4QgKfdxSt+nhl2VXdPjemM5mObBunCjh7LeE",
	"QsqjMx6wRsDC4QoFunX6n34+F5T45DmgCBqCO7b02NeMS9zuHNu26DNoMYfoMnLb9CzvyHORPl8XJaNp",
	"9p7Eg8nPvYhv2DYRxECRWZPr8cT+5BKhLYGxeVuWxxA/TVFElHCd08aCeXQTRJHoyFjM2B+LQ6P/v4dM",
	"34O4+6dGCF0hqbXdOwDVlcvYHP68ZMKBYhrFeqJZDXLNjUYKe36WLrRiYT+Yj6T7Y8nVHb3+WYxYBiBU",
	"1m9njlLwi1r3j/AM6Yd5fG8Yhn73gkSyF/oPxlkI37hmcSRML6+zwXkSPgPtnR4UrVfXGckKl3k9UzQ0",
	"C0El3ZqEyNHBT0wqANQ2yGatOyz2V37NpC3IJFj1tzpUEDL+YPrNnxIhyD43lPJwP0O/6OG+u2vFQhol",
	"ysF75kFZVMQ4ClkQMEm9yACYqS/vXS8k2LSlFolTZPOhvzooqGXGrk6PD+8tYUjzYjkG9SXJ+ctS2+kl",
	"2O9l2YcAM2CKeHQF5mPm/3skOVDbBXiuFcac3S7GVv464Qy+oVviIPEhx1fo4b4UTbv5rRrGjuHGZ+b7",
	"EL8apbIN0njbV7LiYrFDxJ6kMPCo9LuigpNg/cr4mkeKbeyav0OQf++o2lGB0nfQK+Oo9A4igiLK4RvK",
	"z936OYoCSvgpeQeTa59uSBI4OOSB+zAulYhtzAIJk3ZFQr9RyxHq4qRpzVFJyqSphqTbkB6x1CSpUoxv",
	"rVOmqzePRWetb8ugkMRgYSXAUNaVIz53EvsLCRLqIHT4JCXK0PjtEjtZvZM+XRLpdTNR2IaxN6YlADto",
	"G1eWVv5JEO/Iern2Ij+/vDWXrd+JH+1085lXv1hKt0f6RilK71zbeHj6hG5vfvhhfoN04/kSQeMs70u1",
	"BoGIhLGe2ucnSPzI99Qjl6U0c+la6CzC1k+O2z5y3JUFuS0JcjvsMpNTAs4U9dGTgijXnW0fF1wPNWNq",
	"9K3ykn9mYaXb0/pZeSujbdctj7tV14uZ2VtrczPzZfWU7XW4t1DciKSPL4mMFaE3QvnWY7rHVt+SY3Kd",
	"pkg6fxCkP4Z31U2nqqD1/L693TsA15Hcj7+h1mPl3oF78dugzVA6wB+RUk7bKzJW2LZ9xbjJPCCxSYN+",
	"KaFOt95c8e+ErLXxIyLPWl9tOp1+TjCZps5WwnzLr0nEQip7aoLZvSfZBlUHI522e+Aw3H7U1G69o+5R",
	"MfceFeB49/igt6haNk/zapl2PM/IL44cabLd1yIfNfKzwzAaLcJUn2U2oC/H0Xo2Uvm2OwvVpXbI5vnV",
	"j54ZDqmUZNv4Xvq4pqkKgrb/tHmdlyvtzRQKEOvhWmKgxpT5IxW2oTiSTLEX+HLU0GSrzPkqsBVUP6jj",
	"WNz2zOQt3By6kJBFYISE+yJifgHv0uJB6ie5QNm9yYC0Q6KH+xmCADGPeLCvYAv3P8Ftu6KRYv1o3m2C",
	"PHfofILZvaEmmC0cJAnzXXvjdqUkl8HemDZDtIP2TrhtsCuqb4Y3LNA1w2Bm6VqaXcFszbSfLAQ5Go58",
	"uvrkIviMtSBuESjmuWWN1GAYuXKld/1V0X9d1F64k1J6imUnmadW1LWEmnVZyEWdyWZqoLUO/2YeIF08",
	"Tn2kooqkDTuizSlNMYcxw3bPF3omyrWlDD2mT1Eiqd5zPKbr7nS5b096hdScC3Dv6kKnptFJkvbf5LSf",
	"+jYUZeBlIh65hTpUdUFV+73NfZBc1BmYa+E4d4V6EGrMULPvex2I4GraGAwjthEUDQkL2pnmszTcX+iq",
	"NKExw6oRb/WWpwTmzpArojC/Bv1BM8Y3EfScH0sIGYcPPXAaKqQx4Ourm6trG484iRle4dur66tbXfGv",
	"dnoywGlru+hhS2j1/S3VmYxxRhbxB0D2R6qqRaoSV470LK+vjzrI028TsaVmvrap6Dj3g4J0QzeOKwXD",
	"0rBftsfnEiOb4KJ8YEkfHkpCUGC6T+oaYIYV2Uow7zvH068QMSLpgPujoETR2hkCEyeoVH+J/P1gh6Zc",
	"hf7lmAQ5+aGm7Rv4U5XxnCNdVy0ilRzafcCrrgB8GErDRiGuIbpUfJg5PW3xxvyDYZ6AKlo3gXt932kC",
	"JS382bH4WBMEmVF8JBPPo1JukiDYD2b+RtRTwJn1jjbnBpuTY0xvUxsIzB+pOg3J4onPBhrOmyzSE6FA",
	"rTFR3q6uhc+xf8kglOYJfULR9R8oFBm1nBGKulh+SmI/kcmHp+4KV/ci5/Fc4QgCHnZIlyXj4Um0DnZq",
	"m/158QgqnIT7XAbU4mXjE1oXgw1NWU4PGo2URuShY4nnd+SCOXk0uKApfFuX6vHaCcNRKjcRg7SfRTqO",
	"U1yHO6STK9wtC2i6G3Tyibs+fRQbdx+ImphymoWoe4Dz6M3QtNRwvqdTr81+05fMmlTfyW4ukabhu1PB",
	"mh0VSEYlyY7wcQFL1ER6OrJjke2FI9OF+PjdxKeUs8+JT6bGl7Wv8H7MGk1B315eR96fp/N5DPoB6BVm",
	"nuKZo9FF3R+zAuoxfCLDaVp+Lg1bVUdBd0NScF6J7lJCyY57UmtRNV1sattOwp/tM511uOh+TF6cVPHA",
	"eF1YjERrk3jtZbhrUhVaeur23XKBta3kbSUkRznuNNzUcULgKMpyFjAPzF8NY+S6uHc36GI21wGKcfyl",
	"4XzDtJzXIkRVu+6y9IH5sLEGv0urze7WkzebFN/FoU6JJmHUk7GaHRN+xiTerqAzvRkCO5+B60jEfeGg",
	"dBlKf3/GYXl/uBjVOxW4QA5wBuWPSfWNFH8ctU/iPke4zUiM3sNLRmXwNmXVveEEpj6Boien5naL7eP+",
	"k3HwlPZSo9oOzx6fWt9bUPgfULKLMruCgq09byXHp7TNFLxYO99zFDVm0xmUFGUOQApmhkkXET5lxf1j",
	"mHt26mha3isNW9VFfhJqUK7LT0k4dFA05Z7MVlRMF6nZtpPQWes8Z11OOiZ71V1zCvUDdXVgMhJdTeK6",
	"l+GoSR3Y8lKnAyfSHr1rsvHP0hweHZ+FEnsMqD/zGOEHpZ3ETjeFy0y/i3D0CaZxTNb+b5ZJqSYfs/ZP",
	"0q2OhiSZxIBXRTyzzoU5z9e4f5YIQbnKVDCS9zZhYocfFhm9h1bsuA2eftTrxsfBu9BwEtJtmNisNRRd",
	"QsV3wyu3ce4j0erIAeoyhDqRviyVtvjhy3KoKtt/LS9YZ1v8j8iTltoiPe0Rqm0tnFNVtb0s30XJbSbH",
	"O6q67aniVm86o/bW5Vd/xOrb8+PLmWHlPZXg9g8701XhTh6x3lEp7qXiVls1bt+4pf83kHhJTSQRAV7h",
	"BYkZPnw9/DcAAP//Xlym1Mp1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
