// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateAppJSONBodyPlatformId.
const (
	CreateAppJSONBodyPlatformIdAndroid CreateAppJSONBodyPlatformId = "android"
	CreateAppJSONBodyPlatformIdIos     CreateAppJSONBodyPlatformId = "ios"
)

// Defines values for UpdateAppJSONBodyPlatformId.
const (
	UpdateAppJSONBodyPlatformIdAndroid UpdateAppJSONBodyPlatformId = "android"
	UpdateAppJSONBodyPlatformIdIos     UpdateAppJSONBodyPlatformId = "ios"
)

// Defines values for CreateAuctionConfigurationJSONBodyAdType.
const (
	CreateAuctionConfigurationJSONBodyAdTypeBanner       CreateAuctionConfigurationJSONBodyAdType = "banner"
	CreateAuctionConfigurationJSONBodyAdTypeInterstitial CreateAuctionConfigurationJSONBodyAdType = "interstitial"
	CreateAuctionConfigurationJSONBodyAdTypeRewarded     CreateAuctionConfigurationJSONBodyAdType = "rewarded"
)

// Defines values for UpdateAuctionConfigurationJSONBodyAdType.
const (
	UpdateAuctionConfigurationJSONBodyAdTypeBanner       UpdateAuctionConfigurationJSONBodyAdType = "banner"
	UpdateAuctionConfigurationJSONBodyAdTypeInterstitial UpdateAuctionConfigurationJSONBodyAdType = "interstitial"
	UpdateAuctionConfigurationJSONBodyAdTypeRewarded     UpdateAuctionConfigurationJSONBodyAdType = "rewarded"
)

// Defines values for CreateLineItemJSONBodyAdType.
const (
	CreateLineItemJSONBodyAdTypeBanner       CreateLineItemJSONBodyAdType = "banner"
	CreateLineItemJSONBodyAdTypeInterstitial CreateLineItemJSONBodyAdType = "interstitial"
	CreateLineItemJSONBodyAdTypeRewarded     CreateLineItemJSONBodyAdType = "rewarded"
)

// Defines values for CreateLineItemJSONBodyExtra1Format.
const (
	CreateLineItemJSONBodyExtra1FormatBANNER       CreateLineItemJSONBodyExtra1Format = "BANNER"
	CreateLineItemJSONBodyExtra1FormatINTERSTITIAL CreateLineItemJSONBodyExtra1Format = "INTERSTITIAL"
	CreateLineItemJSONBodyExtra1FormatMREC         CreateLineItemJSONBodyExtra1Format = "MREC"
	CreateLineItemJSONBodyExtra1FormatREWARDED     CreateLineItemJSONBodyExtra1Format = "REWARDED"
	CreateLineItemJSONBodyExtra1FormatVIDEO        CreateLineItemJSONBodyExtra1Format = "VIDEO"
)

// Defines values for CreateLineItemJSONBodyFormat.
const (
	CreateLineItemJSONBodyFormatADAPTIVE    CreateLineItemJSONBodyFormat = "ADAPTIVE"
	CreateLineItemJSONBodyFormatBANNER      CreateLineItemJSONBodyFormat = "BANNER"
	CreateLineItemJSONBodyFormatEmpty       CreateLineItemJSONBodyFormat = ""
	CreateLineItemJSONBodyFormatLEADERBOARD CreateLineItemJSONBodyFormat = "LEADERBOARD"
	CreateLineItemJSONBodyFormatMREC        CreateLineItemJSONBodyFormat = "MREC"
)

// Defines values for UpdateLineItemJSONBodyAdType.
const (
	UpdateLineItemJSONBodyAdTypeBanner       UpdateLineItemJSONBodyAdType = "banner"
	UpdateLineItemJSONBodyAdTypeInterstitial UpdateLineItemJSONBodyAdType = "interstitial"
	UpdateLineItemJSONBodyAdTypeRewarded     UpdateLineItemJSONBodyAdType = "rewarded"
)

// Defines values for UpdateLineItemJSONBodyExtra1Format.
const (
	UpdateLineItemJSONBodyExtra1FormatBANNER       UpdateLineItemJSONBodyExtra1Format = "BANNER"
	UpdateLineItemJSONBodyExtra1FormatINTERSTITIAL UpdateLineItemJSONBodyExtra1Format = "INTERSTITIAL"
	UpdateLineItemJSONBodyExtra1FormatMREC         UpdateLineItemJSONBodyExtra1Format = "MREC"
	UpdateLineItemJSONBodyExtra1FormatREWARDED     UpdateLineItemJSONBodyExtra1Format = "REWARDED"
	UpdateLineItemJSONBodyExtra1FormatVIDEO        UpdateLineItemJSONBodyExtra1Format = "VIDEO"
)

// Defines values for UpdateLineItemJSONBodyFormat.
const (
	UpdateLineItemJSONBodyFormatADAPTIVE    UpdateLineItemJSONBodyFormat = "ADAPTIVE"
	UpdateLineItemJSONBodyFormatBANNER      UpdateLineItemJSONBodyFormat = "BANNER"
	UpdateLineItemJSONBodyFormatEmpty       UpdateLineItemJSONBodyFormat = ""
	UpdateLineItemJSONBodyFormatLEADERBOARD UpdateLineItemJSONBodyFormat = "LEADERBOARD"
	UpdateLineItemJSONBodyFormatMREC        UpdateLineItemJSONBodyFormat = "MREC"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyAdType.
const (
	CreateAuctionConfigurationV2JSONBodyAdTypeBanner       CreateAuctionConfigurationV2JSONBodyAdType = "banner"
	CreateAuctionConfigurationV2JSONBodyAdTypeInterstitial CreateAuctionConfigurationV2JSONBodyAdType = "interstitial"
	CreateAuctionConfigurationV2JSONBodyAdTypeRewarded     CreateAuctionConfigurationV2JSONBodyAdType = "rewarded"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyBidding.
const (
	CreateAuctionConfigurationV2JSONBodyBiddingAdmob      CreateAuctionConfigurationV2JSONBodyBidding = "admob"
	CreateAuctionConfigurationV2JSONBodyBiddingAmazon     CreateAuctionConfigurationV2JSONBodyBidding = "amazon"
	CreateAuctionConfigurationV2JSONBodyBiddingApplovin   CreateAuctionConfigurationV2JSONBodyBidding = "applovin"
	CreateAuctionConfigurationV2JSONBodyBiddingBidmachine CreateAuctionConfigurationV2JSONBodyBidding = "bidmachine"
	CreateAuctionConfigurationV2JSONBodyBiddingBigoads    CreateAuctionConfigurationV2JSONBodyBidding = "bigoads"
	CreateAuctionConfigurationV2JSONBodyBiddingChartboost CreateAuctionConfigurationV2JSONBodyBidding = "chartboost"
	CreateAuctionConfigurationV2JSONBodyBiddingDtexchange CreateAuctionConfigurationV2JSONBodyBidding = "dtexchange"
	CreateAuctionConfigurationV2JSONBodyBiddingGam        CreateAuctionConfigurationV2JSONBodyBidding = "gam"
	CreateAuctionConfigurationV2JSONBodyBiddingInmobi     CreateAuctionConfigurationV2JSONBodyBidding = "inmobi"
	CreateAuctionConfigurationV2JSONBodyBiddingIronsource CreateAuctionConfigurationV2JSONBodyBidding = "ironsource"
	CreateAuctionConfigurationV2JSONBodyBiddingMeta       CreateAuctionConfigurationV2JSONBodyBidding = "meta"
	CreateAuctionConfigurationV2JSONBodyBiddingMintegral  CreateAuctionConfigurationV2JSONBodyBidding = "mintegral"
	CreateAuctionConfigurationV2JSONBodyBiddingMobilefuse CreateAuctionConfigurationV2JSONBodyBidding = "mobilefuse"
	CreateAuctionConfigurationV2JSONBodyBiddingUnityads   CreateAuctionConfigurationV2JSONBodyBidding = "unityads"
	CreateAuctionConfigurationV2JSONBodyBiddingVkads      CreateAuctionConfigurationV2JSONBodyBidding = "vkads"
	CreateAuctionConfigurationV2JSONBodyBiddingVungle     CreateAuctionConfigurationV2JSONBodyBidding = "vungle"
	CreateAuctionConfigurationV2JSONBodyBiddingYandex     CreateAuctionConfigurationV2JSONBodyBidding = "yandex"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyDemands.
const (
	CreateAuctionConfigurationV2JSONBodyDemandsAdmob      CreateAuctionConfigurationV2JSONBodyDemands = "admob"
	CreateAuctionConfigurationV2JSONBodyDemandsAmazon     CreateAuctionConfigurationV2JSONBodyDemands = "amazon"
	CreateAuctionConfigurationV2JSONBodyDemandsApplovin   CreateAuctionConfigurationV2JSONBodyDemands = "applovin"
	CreateAuctionConfigurationV2JSONBodyDemandsBidmachine CreateAuctionConfigurationV2JSONBodyDemands = "bidmachine"
	CreateAuctionConfigurationV2JSONBodyDemandsBigoads    CreateAuctionConfigurationV2JSONBodyDemands = "bigoads"
	CreateAuctionConfigurationV2JSONBodyDemandsChartboost CreateAuctionConfigurationV2JSONBodyDemands = "chartboost"
	CreateAuctionConfigurationV2JSONBodyDemandsDtexchange CreateAuctionConfigurationV2JSONBodyDemands = "dtexchange"
	CreateAuctionConfigurationV2JSONBodyDemandsGam        CreateAuctionConfigurationV2JSONBodyDemands = "gam"
	CreateAuctionConfigurationV2JSONBodyDemandsInmobi     CreateAuctionConfigurationV2JSONBodyDemands = "inmobi"
	CreateAuctionConfigurationV2JSONBodyDemandsIronsource CreateAuctionConfigurationV2JSONBodyDemands = "ironsource"
	CreateAuctionConfigurationV2JSONBodyDemandsMeta       CreateAuctionConfigurationV2JSONBodyDemands = "meta"
	CreateAuctionConfigurationV2JSONBodyDemandsMintegral  CreateAuctionConfigurationV2JSONBodyDemands = "mintegral"
	CreateAuctionConfigurationV2JSONBodyDemandsMobilefuse CreateAuctionConfigurationV2JSONBodyDemands = "mobilefuse"
	CreateAuctionConfigurationV2JSONBodyDemandsUnityads   CreateAuctionConfigurationV2JSONBodyDemands = "unityads"
	CreateAuctionConfigurationV2JSONBodyDemandsVkads      CreateAuctionConfigurationV2JSONBodyDemands = "vkads"
	CreateAuctionConfigurationV2JSONBodyDemandsVungle     CreateAuctionConfigurationV2JSONBodyDemands = "vungle"
	CreateAuctionConfigurationV2JSONBodyDemandsYandex     CreateAuctionConfigurationV2JSONBodyDemands = "yandex"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyAdType.
const (
	UpdateAuctionConfigurationV2JSONBodyAdTypeBanner       UpdateAuctionConfigurationV2JSONBodyAdType = "banner"
	UpdateAuctionConfigurationV2JSONBodyAdTypeInterstitial UpdateAuctionConfigurationV2JSONBodyAdType = "interstitial"
	UpdateAuctionConfigurationV2JSONBodyAdTypeRewarded     UpdateAuctionConfigurationV2JSONBodyAdType = "rewarded"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyBidding.
const (
	UpdateAuctionConfigurationV2JSONBodyBiddingAdmob      UpdateAuctionConfigurationV2JSONBodyBidding = "admob"
	UpdateAuctionConfigurationV2JSONBodyBiddingAmazon     UpdateAuctionConfigurationV2JSONBodyBidding = "amazon"
	UpdateAuctionConfigurationV2JSONBodyBiddingApplovin   UpdateAuctionConfigurationV2JSONBodyBidding = "applovin"
	UpdateAuctionConfigurationV2JSONBodyBiddingBidmachine UpdateAuctionConfigurationV2JSONBodyBidding = "bidmachine"
	UpdateAuctionConfigurationV2JSONBodyBiddingBigoads    UpdateAuctionConfigurationV2JSONBodyBidding = "bigoads"
	UpdateAuctionConfigurationV2JSONBodyBiddingChartboost UpdateAuctionConfigurationV2JSONBodyBidding = "chartboost"
	UpdateAuctionConfigurationV2JSONBodyBiddingDtexchange UpdateAuctionConfigurationV2JSONBodyBidding = "dtexchange"
	UpdateAuctionConfigurationV2JSONBodyBiddingGam        UpdateAuctionConfigurationV2JSONBodyBidding = "gam"
	UpdateAuctionConfigurationV2JSONBodyBiddingInmobi     UpdateAuctionConfigurationV2JSONBodyBidding = "inmobi"
	UpdateAuctionConfigurationV2JSONBodyBiddingIronsource UpdateAuctionConfigurationV2JSONBodyBidding = "ironsource"
	UpdateAuctionConfigurationV2JSONBodyBiddingMeta       UpdateAuctionConfigurationV2JSONBodyBidding = "meta"
	UpdateAuctionConfigurationV2JSONBodyBiddingMintegral  UpdateAuctionConfigurationV2JSONBodyBidding = "mintegral"
	UpdateAuctionConfigurationV2JSONBodyBiddingMobilefuse UpdateAuctionConfigurationV2JSONBodyBidding = "mobilefuse"
	UpdateAuctionConfigurationV2JSONBodyBiddingUnityads   UpdateAuctionConfigurationV2JSONBodyBidding = "unityads"
	UpdateAuctionConfigurationV2JSONBodyBiddingVkads      UpdateAuctionConfigurationV2JSONBodyBidding = "vkads"
	UpdateAuctionConfigurationV2JSONBodyBiddingVungle     UpdateAuctionConfigurationV2JSONBodyBidding = "vungle"
	UpdateAuctionConfigurationV2JSONBodyBiddingYandex     UpdateAuctionConfigurationV2JSONBodyBidding = "yandex"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyDemands.
const (
	UpdateAuctionConfigurationV2JSONBodyDemandsAdmob      UpdateAuctionConfigurationV2JSONBodyDemands = "admob"
	UpdateAuctionConfigurationV2JSONBodyDemandsAmazon     UpdateAuctionConfigurationV2JSONBodyDemands = "amazon"
	UpdateAuctionConfigurationV2JSONBodyDemandsApplovin   UpdateAuctionConfigurationV2JSONBodyDemands = "applovin"
	UpdateAuctionConfigurationV2JSONBodyDemandsBidmachine UpdateAuctionConfigurationV2JSONBodyDemands = "bidmachine"
	UpdateAuctionConfigurationV2JSONBodyDemandsBigoads    UpdateAuctionConfigurationV2JSONBodyDemands = "bigoads"
	UpdateAuctionConfigurationV2JSONBodyDemandsChartboost UpdateAuctionConfigurationV2JSONBodyDemands = "chartboost"
	UpdateAuctionConfigurationV2JSONBodyDemandsDtexchange UpdateAuctionConfigurationV2JSONBodyDemands = "dtexchange"
	UpdateAuctionConfigurationV2JSONBodyDemandsGam        UpdateAuctionConfigurationV2JSONBodyDemands = "gam"
	UpdateAuctionConfigurationV2JSONBodyDemandsInmobi     UpdateAuctionConfigurationV2JSONBodyDemands = "inmobi"
	UpdateAuctionConfigurationV2JSONBodyDemandsIronsource UpdateAuctionConfigurationV2JSONBodyDemands = "ironsource"
	UpdateAuctionConfigurationV2JSONBodyDemandsMeta       UpdateAuctionConfigurationV2JSONBodyDemands = "meta"
	UpdateAuctionConfigurationV2JSONBodyDemandsMintegral  UpdateAuctionConfigurationV2JSONBodyDemands = "mintegral"
	UpdateAuctionConfigurationV2JSONBodyDemandsMobilefuse UpdateAuctionConfigurationV2JSONBodyDemands = "mobilefuse"
	UpdateAuctionConfigurationV2JSONBodyDemandsUnityads   UpdateAuctionConfigurationV2JSONBodyDemands = "unityads"
	UpdateAuctionConfigurationV2JSONBodyDemandsVkads      UpdateAuctionConfigurationV2JSONBodyDemands = "vkads"
	UpdateAuctionConfigurationV2JSONBodyDemandsVungle     UpdateAuctionConfigurationV2JSONBodyDemands = "vungle"
	UpdateAuctionConfigurationV2JSONBodyDemandsYandex     UpdateAuctionConfigurationV2JSONBodyDemands = "yandex"
)

// IdParam A positive integer ID
type IdParam = int

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Error code
		Code int `json:"code"`

		// Message Error message
		Message string `json:"message"`
	} `json:"error"`
}

// CreateAppDemandProfileJSONBody defines parameters for CreateAppDemandProfile.
type CreateAppDemandProfileJSONBody struct {
	// AccountId A positive integer ID
	AccountId int `json:"account_id"`

	// AccountType The type of account associated with this demand profile
	AccountType string `json:"account_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Data Additional data associated with the demand profile
	Data map[string]interface{} `json:"data"`

	// DemandSourceId A positive integer ID
	DemandSourceId int `json:"demand_source_id"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// UpdateAppDemandProfileJSONBody defines parameters for UpdateAppDemandProfile.
type UpdateAppDemandProfileJSONBody struct {
	// AccountId A positive integer ID
	AccountId *int `json:"account_id,omitempty"`

	// AccountType The type of account associated with this demand profile
	AccountType *string `json:"account_type,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Data Additional data associated with the demand profile
	Data *map[string]interface{} `json:"data,omitempty"`

	// DemandSourceId A positive integer ID
	DemandSourceId *int `json:"demand_source_id,omitempty"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// CreateAppJSONBody defines parameters for CreateApp.
type CreateAppJSONBody struct {
	// AppKey A unique key for the app
	AppKey string `json:"app_key"`

	// HumanName The human-readable name of the app
	HumanName string `json:"human_name"`

	// Id A positive integer ID
	Id int `json:"id"`

	// PackageName The package name of the app
	PackageName string                      `json:"package_name"`
	PlatformId  CreateAppJSONBodyPlatformId `json:"platform_id"`
	PublicUid   *openapi_types.UUID         `json:"public_uid,omitempty"`

	// UserId A positive integer ID
	UserId int `json:"user_id"`
}

// CreateAppJSONBodyPlatformId defines parameters for CreateApp.
type CreateAppJSONBodyPlatformId string

// UpdateAppJSONBody defines parameters for UpdateApp.
type UpdateAppJSONBody struct {
	// AppKey A unique key for the app
	AppKey *string `json:"app_key,omitempty"`

	// HumanName The human-readable name of the app
	HumanName *string `json:"human_name,omitempty"`

	// Id A positive integer ID
	Id *int `json:"id,omitempty"`

	// PackageName The package name of the app
	PackageName *string                      `json:"package_name,omitempty"`
	PlatformId  *UpdateAppJSONBodyPlatformId `json:"platform_id,omitempty"`
	PublicUid   *openapi_types.UUID          `json:"public_uid,omitempty"`

	// UserId A positive integer ID
	UserId *int `json:"user_id,omitempty"`
}

// UpdateAppJSONBodyPlatformId defines parameters for UpdateApp.
type UpdateAppJSONBodyPlatformId string

// CreateAuctionConfigurationJSONBody defines parameters for CreateAuctionConfiguration.
type CreateAuctionConfigurationJSONBody struct {
	AdType CreateAuctionConfigurationJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name Name of the auction configuration
	Name string `json:"name"`

	// Pricefloor Price floor for the auction configuration
	Pricefloor float32             `json:"pricefloor"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// Rounds Auction rounds
	Rounds []struct {
		// Demands List of demands for the round
		Demands []string `json:"demands"`

		// Id Round ID
		Id string `json:"id"`

		// Timeout Timeout for the round in milliseconds
		Timeout int `json:"timeout"`
	} `json:"rounds"`
}

// CreateAuctionConfigurationJSONBodyAdType defines parameters for CreateAuctionConfiguration.
type CreateAuctionConfigurationJSONBodyAdType string

// UpdateAuctionConfigurationJSONBody defines parameters for UpdateAuctionConfiguration.
type UpdateAuctionConfigurationJSONBody struct {
	AdType UpdateAuctionConfigurationJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name Name of the auction configuration
	Name string `json:"name"`

	// Pricefloor Price floor for the auction configuration
	Pricefloor float32             `json:"pricefloor"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// Rounds Auction rounds
	Rounds []struct {
		// Demands List of demands for the round
		Demands []string `json:"demands"`

		// Id Round ID
		Id string `json:"id"`

		// Timeout Timeout for the round in milliseconds
		Timeout int `json:"timeout"`
	} `json:"rounds"`
}

// UpdateAuctionConfigurationJSONBodyAdType defines parameters for UpdateAuctionConfiguration.
type UpdateAuctionConfigurationJSONBodyAdType string

// CreateCountryJSONBody defines parameters for CreateCountry.
type CreateCountryJSONBody struct {
	// Alpha2Code The ISO 3166-1 alpha-2 code for the country
	Alpha2Code string `json:"alpha_2_code"`

	// Alpha3Code The ISO 3166-1 alpha-3 code for the country
	Alpha3Code string `json:"alpha_3_code"`

	// HumanName The human-readable name of the country
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// UpdateCountryJSONBody defines parameters for UpdateCountry.
type UpdateCountryJSONBody struct {
	// Alpha2Code The ISO 3166-1 alpha-2 code for the country
	Alpha2Code *string `json:"alpha_2_code,omitempty"`

	// Alpha3Code The ISO 3166-1 alpha-3 code for the country
	Alpha3Code *string `json:"alpha_3_code,omitempty"`

	// HumanName The human-readable name of the country
	HumanName *string `json:"human_name,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// CreateDemandSourceAccountJSONBody defines parameters for CreateDemandSourceAccount.
type CreateDemandSourceAccountJSONBody struct {
	// DemandSourceId A positive integer ID
	DemandSourceId int `json:"demand_source_id"`

	// Extra Additional information for the demand source account
	Extra map[string]interface{} `json:"extra"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsBidding Indicates whether bidding is enabled for this demand source account
	IsBidding bool               `json:"is_bidding"`
	PublicUid openapi_types.UUID `json:"public_uid"`

	// Type The type of the demand source account
	Type string `json:"type"`

	// UserId A positive integer ID
	UserId int `json:"user_id"`
}

// UpdateDemandSourceAccountJSONBody defines parameters for UpdateDemandSourceAccount.
type UpdateDemandSourceAccountJSONBody struct {
	// DemandSourceId A positive integer ID
	DemandSourceId *int `json:"demand_source_id,omitempty"`

	// Extra Additional information for the demand source account
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsBidding Indicates whether bidding is enabled for this demand source account
	IsBidding *bool               `json:"is_bidding,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`

	// Type The type of the demand source account
	Type *string `json:"type,omitempty"`

	// UserId A positive integer ID
	UserId *int `json:"user_id,omitempty"`
}

// CreateDemandSourceJSONBody defines parameters for CreateDemandSource.
type CreateDemandSourceJSONBody struct {
	// ApiKey The API key associated with the demand source
	ApiKey string `json:"api_key"`

	// HumanName The human-readable name of the demand source
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// UpdateDemandSourceJSONBody defines parameters for UpdateDemandSource.
type UpdateDemandSourceJSONBody struct {
	// ApiKey The API key associated with the demand source
	ApiKey string `json:"api_key"`

	// HumanName The human-readable name of the demand source
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// GetLineItemsParams defines parameters for GetLineItems.
type GetLineItemsParams struct {
	// UserId Filter by user ID
	UserId *int64 `form:"user_id,omitempty" json:"user_id,omitempty"`

	// AppId Filter by app ID
	AppId *int64 `form:"app_id,omitempty" json:"app_id,omitempty"`

	// AdType Filter by ad type
	AdType *interface{} `form:"ad_type,omitempty" json:"ad_type,omitempty"`

	// AccountId Filter by account ID
	AccountId *int64 `form:"account_id,omitempty" json:"account_id,omitempty"`

	// AccountType Filter by account type
	AccountType *string `form:"account_type,omitempty" json:"account_type,omitempty"`

	// IsBidding Filter by bidding status
	IsBidding *bool `form:"is_bidding,omitempty" json:"is_bidding,omitempty"`
}

// CreateLineItemJSONBody defines parameters for CreateLineItem.
type CreateLineItemJSONBody struct {
	// AccountId A positive integer ID
	AccountId int `json:"account_id"`

	// AccountType The type of account
	AccountType string                       `json:"account_type"`
	AdType      CreateLineItemJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// BidFloor The minimum bid floor price
	BidFloor string `json:"bid_floor"`

	// Code The unique code for the line item
	Code  string                       `json:"code"`
	Extra CreateLineItemJSONBody_Extra `json:"extra"`

	// Format The format of the ad
	Format CreateLineItemJSONBodyFormat `json:"format"`

	// HumanName The human-readable name of the line item
	HumanName string `json:"human_name"`

	// Id A positive integer primary ID, read-only
	Id        *int               `json:"id,omitempty"`
	PublicUid openapi_types.UUID `json:"public_uid"`
}

// CreateLineItemJSONBodyAdType defines parameters for CreateLineItem.
type CreateLineItemJSONBodyAdType string

// CreateLineItemJSONBodyExtra0 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra0 struct {
	// AdUnitId Ad unit ID (for Admob, Yandex)
	AdUnitId string `json:"ad_unit_id"`
}

// CreateLineItemJSONBodyExtra1 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra1 struct {
	// Format Ad format
	Format CreateLineItemJSONBodyExtra1Format `json:"format"`

	// SlotUuid Slot UUID (for Amazon)
	SlotUuid string `json:"slot_uuid"`
}

// CreateLineItemJSONBodyExtra1Format defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra1Format string

// CreateLineItemJSONBodyExtra2 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra2 struct {
	// ZoneId Zone ID (for Applovin)
	ZoneId string `json:"zone_id"`
}

// CreateLineItemJSONBodyExtra3 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra3 struct {
	// SlotId Slot ID (for BigoAds, VKAds)
	SlotId string `json:"slot_id"`
}

// CreateLineItemJSONBodyExtra4 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra4 struct {
	// AdLocation Ad location (for Chartboost)
	AdLocation string `json:"ad_location"`

	// Mediation Optional mediation parameter
	Mediation *string `json:"mediation,omitempty"`
}

// CreateLineItemJSONBodyExtra5 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra5 struct {
	// PlacementId Placement ID (for Meta, UnityAds, Vungle, MobileFuse)
	PlacementId string `json:"placement_id"`
}

// CreateLineItemJSONBodyExtra6 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra6 struct {
	// SpotId Spot ID (for DTExchange)
	SpotId string `json:"spot_id"`
}

// CreateLineItemJSONBodyExtra7 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra7 struct {
	// InstanceId Instance ID (for IronSource)
	InstanceId string `json:"instance_id"`
}

// CreateLineItemJSONBodyExtra8 defines parameters for CreateLineItem.
type CreateLineItemJSONBodyExtra8 struct {
	// PlacementId Placement ID (for Mintegral)
	PlacementId string `json:"placement_id"`

	// UnitId Unit ID (for Mintegral)
	UnitId string `json:"unit_id"`
}

// CreateLineItemJSONBody_Extra defines parameters for CreateLineItem.
type CreateLineItemJSONBody_Extra struct {
	union json.RawMessage
}

// CreateLineItemJSONBodyFormat defines parameters for CreateLineItem.
type CreateLineItemJSONBodyFormat string

// UpdateLineItemJSONBody defines parameters for UpdateLineItem.
type UpdateLineItemJSONBody struct {
	// AccountId A positive integer ID
	AccountId *int `json:"account_id,omitempty"`

	// AccountType The type of account
	AccountType *string                       `json:"account_type,omitempty"`
	AdType      *UpdateLineItemJSONBodyAdType `json:"ad_type,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// BidFloor The minimum bid floor price
	BidFloor *string `json:"bid_floor,omitempty"`

	// Code The unique code for the line item
	Code  *string                       `json:"code,omitempty"`
	Extra *UpdateLineItemJSONBody_Extra `json:"extra,omitempty"`

	// Format The format of the ad
	Format *UpdateLineItemJSONBodyFormat `json:"format,omitempty"`

	// HumanName The human-readable name of the line item
	HumanName *string `json:"human_name,omitempty"`

	// Id A positive integer primary ID, read-only
	Id        *int                `json:"id,omitempty"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// UpdateLineItemJSONBodyAdType defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyAdType string

// UpdateLineItemJSONBodyExtra0 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra0 struct {
	// AdUnitId Ad unit ID (for Admob, Yandex)
	AdUnitId string `json:"ad_unit_id"`
}

// UpdateLineItemJSONBodyExtra1 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra1 struct {
	// Format Ad format
	Format UpdateLineItemJSONBodyExtra1Format `json:"format"`

	// SlotUuid Slot UUID (for Amazon)
	SlotUuid string `json:"slot_uuid"`
}

// UpdateLineItemJSONBodyExtra1Format defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra1Format string

// UpdateLineItemJSONBodyExtra2 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra2 struct {
	// ZoneId Zone ID (for Applovin)
	ZoneId string `json:"zone_id"`
}

// UpdateLineItemJSONBodyExtra3 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra3 struct {
	// SlotId Slot ID (for BigoAds, VKAds)
	SlotId string `json:"slot_id"`
}

// UpdateLineItemJSONBodyExtra4 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra4 struct {
	// AdLocation Ad location (for Chartboost)
	AdLocation string `json:"ad_location"`

	// Mediation Optional mediation parameter
	Mediation *string `json:"mediation,omitempty"`
}

// UpdateLineItemJSONBodyExtra5 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra5 struct {
	// PlacementId Placement ID (for Meta, UnityAds, Vungle, MobileFuse)
	PlacementId string `json:"placement_id"`
}

// UpdateLineItemJSONBodyExtra6 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra6 struct {
	// SpotId Spot ID (for DTExchange)
	SpotId string `json:"spot_id"`
}

// UpdateLineItemJSONBodyExtra7 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra7 struct {
	// InstanceId Instance ID (for IronSource)
	InstanceId string `json:"instance_id"`
}

// UpdateLineItemJSONBodyExtra8 defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyExtra8 struct {
	// PlacementId Placement ID (for Mintegral)
	PlacementId string `json:"placement_id"`

	// UnitId Unit ID (for Mintegral)
	UnitId string `json:"unit_id"`
}

// UpdateLineItemJSONBody_Extra defines parameters for UpdateLineItem.
type UpdateLineItemJSONBody_Extra struct {
	union json.RawMessage
}

// UpdateLineItemJSONBodyFormat defines parameters for UpdateLineItem.
type UpdateLineItemJSONBodyFormat string

// CreateSegmentJSONBody defines parameters for CreateSegment.
type CreateSegmentJSONBody struct {
	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Description The description of the segment
	Description string `json:"description"`

	// Enabled Indicates if the segment is enabled
	Enabled bool `json:"enabled"`

	// Filters Filters applied to the segment
	Filters []struct {
		// Name The name of the filter
		Name string `json:"name"`

		// Operator The operator used in the filter
		Operator string `json:"operator"`

		// Type The type of filter
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"filters"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name The name of the segment
	Name      string             `json:"name"`
	PublicUid openapi_types.UUID `json:"public_uid"`
}

// UpdateSegmentJSONBody defines parameters for UpdateSegment.
type UpdateSegmentJSONBody struct {
	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Description The description of the segment
	Description string `json:"description"`

	// Enabled Indicates if the segment is enabled
	Enabled bool `json:"enabled"`

	// Filters Filters applied to the segment
	Filters []struct {
		// Name The name of the filter
		Name string `json:"name"`

		// Operator The operator used in the filter
		Operator string `json:"operator"`

		// Type The type of filter
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"filters"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name The name of the segment
	Name      string              `json:"name"`
	PublicUid *openapi_types.UUID `json:"public_uid,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	Email openapi_types.Email `json:"email"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`
}

// CreateAuctionConfigurationV2JSONBody defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBody struct {
	AdType CreateAuctionConfigurationV2JSONBodyAdType `json:"ad_type"`

	// AdUnitIds List of ad unit IDs
	AdUnitIds *[]int `json:"ad_unit_ids,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Bidding List of bidding sources
	Bidding *[]CreateAuctionConfigurationV2JSONBodyBidding `json:"bidding,omitempty"`

	// Demands List of demand sources
	Demands *[]CreateAuctionConfigurationV2JSONBodyDemands `json:"demands,omitempty"`

	// ExternalWinNotifications Whether external win notifications are enabled
	ExternalWinNotifications *bool `json:"external_win_notifications,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsDefault Indicates if this is the default configuration
	IsDefault  *bool               `json:"is_default,omitempty"`
	Name       string              `json:"name"`
	Pricefloor float32             `json:"pricefloor"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// SegmentId A positive integer ID
	SegmentId *int `json:"segment_id,omitempty"`

	// Settings A map of configuration settings
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// Timeout Timeout value in milliseconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// CreateAuctionConfigurationV2JSONBodyAdType defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyAdType string

// CreateAuctionConfigurationV2JSONBodyBidding defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyBidding string

// CreateAuctionConfigurationV2JSONBodyDemands defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyDemands string

// UpdateAuctionConfigurationV2JSONBody defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBody struct {
	AdType *UpdateAuctionConfigurationV2JSONBodyAdType `json:"ad_type,omitempty"`

	// AdUnitIds List of ad unit IDs
	AdUnitIds *[]int `json:"ad_unit_ids,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Bidding List of bidding sources
	Bidding *[]UpdateAuctionConfigurationV2JSONBodyBidding `json:"bidding,omitempty"`

	// Demands List of demand sources
	Demands *[]UpdateAuctionConfigurationV2JSONBodyDemands `json:"demands,omitempty"`

	// ExternalWinNotifications Whether external win notifications are enabled
	ExternalWinNotifications *bool `json:"external_win_notifications,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsDefault Indicates if this is the default configuration
	IsDefault  *bool               `json:"is_default,omitempty"`
	Name       *string             `json:"name,omitempty"`
	Pricefloor *float32            `json:"pricefloor,omitempty"`
	PublicUid  *openapi_types.UUID `json:"public_uid,omitempty"`

	// SegmentId A positive integer ID
	SegmentId *int `json:"segment_id,omitempty"`

	// Settings A map of configuration settings
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// Timeout Timeout value in milliseconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// UpdateAuctionConfigurationV2JSONBodyAdType defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyAdType string

// UpdateAuctionConfigurationV2JSONBodyBidding defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyBidding string

// UpdateAuctionConfigurationV2JSONBodyDemands defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyDemands string

// CreateAppDemandProfileJSONRequestBody defines body for CreateAppDemandProfile for application/json ContentType.
type CreateAppDemandProfileJSONRequestBody CreateAppDemandProfileJSONBody

// UpdateAppDemandProfileJSONRequestBody defines body for UpdateAppDemandProfile for application/json ContentType.
type UpdateAppDemandProfileJSONRequestBody UpdateAppDemandProfileJSONBody

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody CreateAppJSONBody

// UpdateAppJSONRequestBody defines body for UpdateApp for application/json ContentType.
type UpdateAppJSONRequestBody UpdateAppJSONBody

// CreateAuctionConfigurationJSONRequestBody defines body for CreateAuctionConfiguration for application/json ContentType.
type CreateAuctionConfigurationJSONRequestBody CreateAuctionConfigurationJSONBody

// UpdateAuctionConfigurationJSONRequestBody defines body for UpdateAuctionConfiguration for application/json ContentType.
type UpdateAuctionConfigurationJSONRequestBody UpdateAuctionConfigurationJSONBody

// CreateCountryJSONRequestBody defines body for CreateCountry for application/json ContentType.
type CreateCountryJSONRequestBody CreateCountryJSONBody

// UpdateCountryJSONRequestBody defines body for UpdateCountry for application/json ContentType.
type UpdateCountryJSONRequestBody UpdateCountryJSONBody

// CreateDemandSourceAccountJSONRequestBody defines body for CreateDemandSourceAccount for application/json ContentType.
type CreateDemandSourceAccountJSONRequestBody CreateDemandSourceAccountJSONBody

// UpdateDemandSourceAccountJSONRequestBody defines body for UpdateDemandSourceAccount for application/json ContentType.
type UpdateDemandSourceAccountJSONRequestBody UpdateDemandSourceAccountJSONBody

// CreateDemandSourceJSONRequestBody defines body for CreateDemandSource for application/json ContentType.
type CreateDemandSourceJSONRequestBody CreateDemandSourceJSONBody

// UpdateDemandSourceJSONRequestBody defines body for UpdateDemandSource for application/json ContentType.
type UpdateDemandSourceJSONRequestBody UpdateDemandSourceJSONBody

// CreateLineItemJSONRequestBody defines body for CreateLineItem for application/json ContentType.
type CreateLineItemJSONRequestBody CreateLineItemJSONBody

// UpdateLineItemJSONRequestBody defines body for UpdateLineItem for application/json ContentType.
type UpdateLineItemJSONRequestBody UpdateLineItemJSONBody

// CreateSegmentJSONRequestBody defines body for CreateSegment for application/json ContentType.
type CreateSegmentJSONRequestBody CreateSegmentJSONBody

// UpdateSegmentJSONRequestBody defines body for UpdateSegment for application/json ContentType.
type UpdateSegmentJSONRequestBody UpdateSegmentJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// CreateAuctionConfigurationV2JSONRequestBody defines body for CreateAuctionConfigurationV2 for application/json ContentType.
type CreateAuctionConfigurationV2JSONRequestBody CreateAuctionConfigurationV2JSONBody

// UpdateAuctionConfigurationV2JSONRequestBody defines body for UpdateAuctionConfigurationV2 for application/json ContentType.
type UpdateAuctionConfigurationV2JSONRequestBody UpdateAuctionConfigurationV2JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List app demand profiles
	// (GET /app_demand_profiles)
	GetAppDemandProfiles(ctx echo.Context) error
	// Create app demand profile
	// (POST /app_demand_profiles)
	CreateAppDemandProfile(ctx echo.Context) error
	// Delete app demand profile
	// (DELETE /app_demand_profiles/{id})
	DeleteAppDemandProfile(ctx echo.Context, id IdParam) error
	// Get app demand profile
	// (GET /app_demand_profiles/{id})
	GetAppDemandProfile(ctx echo.Context, id IdParam) error
	// Update app demand profile
	// (PATCH /app_demand_profiles/{id})
	UpdateAppDemandProfile(ctx echo.Context, id IdParam) error
	// List apps
	// (GET /apps)
	GetApps(ctx echo.Context) error
	// Create app
	// (POST /apps)
	CreateApp(ctx echo.Context) error
	// Delete app
	// (DELETE /apps/{id})
	DeleteApp(ctx echo.Context, id IdParam) error
	// Get app
	// (GET /apps/{id})
	GetApp(ctx echo.Context, id IdParam) error
	// Update app
	// (PATCH /apps/{id})
	UpdateApp(ctx echo.Context, id IdParam) error
	// List auction configurations
	// (GET /auction_configurations)
	GetAuctionConfigurations(ctx echo.Context) error
	// Create auction configuration
	// (POST /auction_configurations)
	CreateAuctionConfiguration(ctx echo.Context) error
	// Delete auction configuration
	// (DELETE /auction_configurations/{id})
	DeleteAuctionConfiguration(ctx echo.Context, id IdParam) error
	// Get auction configuration
	// (GET /auction_configurations/{id})
	GetAuctionConfiguration(ctx echo.Context, id IdParam) error
	// Update auction configuration
	// (PATCH /auction_configurations/{id})
	UpdateAuctionConfiguration(ctx echo.Context, id IdParam) error
	// List countries
	// (GET /countries)
	GetCountries(ctx echo.Context) error
	// Create country
	// (POST /countries)
	CreateCountry(ctx echo.Context) error
	// Delete country
	// (DELETE /countries/{id})
	DeleteCountry(ctx echo.Context, id IdParam) error
	// Get country
	// (GET /countries/{id})
	GetCountry(ctx echo.Context, id IdParam) error
	// Update country
	// (PATCH /countries/{id})
	UpdateCountry(ctx echo.Context, id IdParam) error
	// List demand source accounts
	// (GET /demand_source_accounts)
	GetDemandSourceAccounts(ctx echo.Context) error
	// Create demand source account
	// (POST /demand_source_accounts)
	CreateDemandSourceAccount(ctx echo.Context) error
	// Delete demand source account
	// (DELETE /demand_source_accounts/{id})
	DeleteDemandSourceAccount(ctx echo.Context, id IdParam) error
	// Get demand source account
	// (GET /demand_source_accounts/{id})
	GetDemandSourceAccount(ctx echo.Context, id IdParam) error
	// Update demand source account
	// (PATCH /demand_source_accounts/{id})
	UpdateDemandSourceAccount(ctx echo.Context, id IdParam) error
	// List demand sources
	// (GET /demand_sources)
	GetDemandSources(ctx echo.Context) error
	// Create demand source
	// (POST /demand_sources)
	CreateDemandSource(ctx echo.Context) error
	// Delete demand source
	// (DELETE /demand_sources/{id})
	DeleteDemandSource(ctx echo.Context, id IdParam) error
	// Get demand source
	// (GET /demand_sources/{id})
	GetDemandSource(ctx echo.Context, id IdParam) error
	// Update demand source
	// (PATCH /demand_sources/{id})
	UpdateDemandSource(ctx echo.Context, id IdParam) error
	// List line items
	// (GET /line_items)
	GetLineItems(ctx echo.Context, params GetLineItemsParams) error
	// Create line item
	// (POST /line_items)
	CreateLineItem(ctx echo.Context) error
	// Delete line item
	// (DELETE /line_items/{id})
	DeleteLineItem(ctx echo.Context, id IdParam) error
	// Get line item
	// (GET /line_items/{id})
	GetLineItem(ctx echo.Context, id IdParam) error
	// Update line item
	// (PATCH /line_items/{id})
	UpdateLineItem(ctx echo.Context, id IdParam) error
	// List segments
	// (GET /segments)
	GetSegments(ctx echo.Context) error
	// Create segment
	// (POST /segments)
	CreateSegment(ctx echo.Context) error
	// Delete segment
	// (DELETE /segments/{id})
	DeleteSegment(ctx echo.Context, id IdParam) error
	// Get segment
	// (GET /segments/{id})
	GetSegment(ctx echo.Context, id IdParam) error
	// Update segment
	// (PATCH /segments/{id})
	UpdateSegment(ctx echo.Context, id IdParam) error
	// List users
	// (GET /users)
	GetUsers(ctx echo.Context) error
	// Create user
	// (POST /users)
	CreateUser(ctx echo.Context) error
	// Get current user
	// (GET /users/me)
	GetCurrentUser(ctx echo.Context) error
	// Delete user
	// (DELETE /users/{id})
	DeleteUser(ctx echo.Context, id IdParam) error
	// Get user
	// (GET /users/{id})
	GetUser(ctx echo.Context, id IdParam) error
	// Update user
	// (PATCH /users/{id})
	UpdateUser(ctx echo.Context, id IdParam) error
	// List auction configurations V2
	// (GET /v2/auction_configurations)
	GetAuctionConfigurationsV2(ctx echo.Context) error
	// Create auction configuration V2
	// (POST /v2/auction_configurations)
	CreateAuctionConfigurationV2(ctx echo.Context) error
	// Delete auction configuration
	// (DELETE /v2/auction_configurations/{id})
	DeleteAuctionConfigurationV2(ctx echo.Context, id IdParam) error
	// Get auction configuration V2
	// (GET /v2/auction_configurations/{id})
	GetAuctionConfigurationV2(ctx echo.Context, id IdParam) error
	// Update auction configuration V2
	// (PATCH /v2/auction_configurations/{id})
	UpdateAuctionConfigurationV2(ctx echo.Context, id IdParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAppDemandProfiles converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppDemandProfiles(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAppDemandProfiles(ctx)
	return err
}

// CreateAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAppDemandProfile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAppDemandProfile(ctx)
	return err
}

// DeleteAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAppDemandProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAppDemandProfile(ctx, id)
	return err
}

// GetAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppDemandProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAppDemandProfile(ctx, id)
	return err
}

// UpdateAppDemandProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAppDemandProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAppDemandProfile(ctx, id)
	return err
}

// GetApps converts echo context to params.
func (w *ServerInterfaceWrapper) GetApps(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApps(ctx)
	return err
}

// CreateApp converts echo context to params.
func (w *ServerInterfaceWrapper) CreateApp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateApp(ctx)
	return err
}

// DeleteApp converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApp(ctx, id)
	return err
}

// GetApp converts echo context to params.
func (w *ServerInterfaceWrapper) GetApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApp(ctx, id)
	return err
}

// UpdateApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateApp(ctx, id)
	return err
}

// GetAuctionConfigurations converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurations(ctx)
	return err
}

// CreateAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuctionConfiguration(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuctionConfiguration(ctx)
	return err
}

// DeleteAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuctionConfiguration(ctx, id)
	return err
}

// GetAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfiguration(ctx, id)
	return err
}

// UpdateAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuctionConfiguration(ctx, id)
	return err
}

// GetCountries converts echo context to params.
func (w *ServerInterfaceWrapper) GetCountries(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCountries(ctx)
	return err
}

// CreateCountry converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCountry(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCountry(ctx)
	return err
}

// DeleteCountry converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCountry(ctx, id)
	return err
}

// GetCountry converts echo context to params.
func (w *ServerInterfaceWrapper) GetCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCountry(ctx, id)
	return err
}

// UpdateCountry converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCountry(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCountry(ctx, id)
	return err
}

// GetDemandSourceAccounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSourceAccounts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSourceAccounts(ctx)
	return err
}

// CreateDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDemandSourceAccount(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDemandSourceAccount(ctx)
	return err
}

// DeleteDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDemandSourceAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDemandSourceAccount(ctx, id)
	return err
}

// GetDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSourceAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSourceAccount(ctx, id)
	return err
}

// UpdateDemandSourceAccount converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDemandSourceAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDemandSourceAccount(ctx, id)
	return err
}

// GetDemandSources converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSources(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSources(ctx)
	return err
}

// CreateDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDemandSource(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDemandSource(ctx)
	return err
}

// DeleteDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDemandSource(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDemandSource(ctx, id)
	return err
}

// GetDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) GetDemandSource(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDemandSource(ctx, id)
	return err
}

// UpdateDemandSource converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDemandSource(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDemandSource(ctx, id)
	return err
}

// GetLineItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetLineItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLineItemsParams
	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// ------------- Optional query parameter "app_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "app_id", ctx.QueryParams(), &params.AppId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter app_id: %s", err))
	}

	// ------------- Optional query parameter "ad_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "ad_type", ctx.QueryParams(), &params.AdType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ad_type: %s", err))
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_id", ctx.QueryParams(), &params.AccountId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	// ------------- Optional query parameter "account_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_type", ctx.QueryParams(), &params.AccountType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_type: %s", err))
	}

	// ------------- Optional query parameter "is_bidding" -------------

	err = runtime.BindQueryParameter("form", true, false, "is_bidding", ctx.QueryParams(), &params.IsBidding)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter is_bidding: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLineItems(ctx, params)
	return err
}

// CreateLineItem converts echo context to params.
func (w *ServerInterfaceWrapper) CreateLineItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateLineItem(ctx)
	return err
}

// DeleteLineItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLineItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteLineItem(ctx, id)
	return err
}

// GetLineItem converts echo context to params.
func (w *ServerInterfaceWrapper) GetLineItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLineItem(ctx, id)
	return err
}

// UpdateLineItem converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateLineItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateLineItem(ctx, id)
	return err
}

// GetSegments converts echo context to params.
func (w *ServerInterfaceWrapper) GetSegments(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSegments(ctx)
	return err
}

// CreateSegment converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSegment(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSegment(ctx)
	return err
}

// DeleteSegment converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSegment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSegment(ctx, id)
	return err
}

// GetSegment converts echo context to params.
func (w *ServerInterfaceWrapper) GetSegment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSegment(ctx, id)
	return err
}

// UpdateSegment converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSegment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSegment(ctx, id)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// GetAuctionConfigurationsV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurationsV2(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurationsV2(ctx)
	return err
}

// CreateAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuctionConfigurationV2(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuctionConfigurationV2(ctx)
	return err
}

// DeleteAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuctionConfigurationV2(ctx, id)
	return err
}

// GetAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurationV2(ctx, id)
	return err
}

// UpdateAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuctionConfigurationV2(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/app_demand_profiles", wrapper.GetAppDemandProfiles)
	router.POST(baseURL+"/app_demand_profiles", wrapper.CreateAppDemandProfile)
	router.DELETE(baseURL+"/app_demand_profiles/:id", wrapper.DeleteAppDemandProfile)
	router.GET(baseURL+"/app_demand_profiles/:id", wrapper.GetAppDemandProfile)
	router.PATCH(baseURL+"/app_demand_profiles/:id", wrapper.UpdateAppDemandProfile)
	router.GET(baseURL+"/apps", wrapper.GetApps)
	router.POST(baseURL+"/apps", wrapper.CreateApp)
	router.DELETE(baseURL+"/apps/:id", wrapper.DeleteApp)
	router.GET(baseURL+"/apps/:id", wrapper.GetApp)
	router.PATCH(baseURL+"/apps/:id", wrapper.UpdateApp)
	router.GET(baseURL+"/auction_configurations", wrapper.GetAuctionConfigurations)
	router.POST(baseURL+"/auction_configurations", wrapper.CreateAuctionConfiguration)
	router.DELETE(baseURL+"/auction_configurations/:id", wrapper.DeleteAuctionConfiguration)
	router.GET(baseURL+"/auction_configurations/:id", wrapper.GetAuctionConfiguration)
	router.PATCH(baseURL+"/auction_configurations/:id", wrapper.UpdateAuctionConfiguration)
	router.GET(baseURL+"/countries", wrapper.GetCountries)
	router.POST(baseURL+"/countries", wrapper.CreateCountry)
	router.DELETE(baseURL+"/countries/:id", wrapper.DeleteCountry)
	router.GET(baseURL+"/countries/:id", wrapper.GetCountry)
	router.PATCH(baseURL+"/countries/:id", wrapper.UpdateCountry)
	router.GET(baseURL+"/demand_source_accounts", wrapper.GetDemandSourceAccounts)
	router.POST(baseURL+"/demand_source_accounts", wrapper.CreateDemandSourceAccount)
	router.DELETE(baseURL+"/demand_source_accounts/:id", wrapper.DeleteDemandSourceAccount)
	router.GET(baseURL+"/demand_source_accounts/:id", wrapper.GetDemandSourceAccount)
	router.PATCH(baseURL+"/demand_source_accounts/:id", wrapper.UpdateDemandSourceAccount)
	router.GET(baseURL+"/demand_sources", wrapper.GetDemandSources)
	router.POST(baseURL+"/demand_sources", wrapper.CreateDemandSource)
	router.DELETE(baseURL+"/demand_sources/:id", wrapper.DeleteDemandSource)
	router.GET(baseURL+"/demand_sources/:id", wrapper.GetDemandSource)
	router.PATCH(baseURL+"/demand_sources/:id", wrapper.UpdateDemandSource)
	router.GET(baseURL+"/line_items", wrapper.GetLineItems)
	router.POST(baseURL+"/line_items", wrapper.CreateLineItem)
	router.DELETE(baseURL+"/line_items/:id", wrapper.DeleteLineItem)
	router.GET(baseURL+"/line_items/:id", wrapper.GetLineItem)
	router.PATCH(baseURL+"/line_items/:id", wrapper.UpdateLineItem)
	router.GET(baseURL+"/segments", wrapper.GetSegments)
	router.POST(baseURL+"/segments", wrapper.CreateSegment)
	router.DELETE(baseURL+"/segments/:id", wrapper.DeleteSegment)
	router.GET(baseURL+"/segments/:id", wrapper.GetSegment)
	router.PATCH(baseURL+"/segments/:id", wrapper.UpdateSegment)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.POST(baseURL+"/users", wrapper.CreateUser)
	router.GET(baseURL+"/users/me", wrapper.GetCurrentUser)
	router.DELETE(baseURL+"/users/:id", wrapper.DeleteUser)
	router.GET(baseURL+"/users/:id", wrapper.GetUser)
	router.PATCH(baseURL+"/users/:id", wrapper.UpdateUser)
	router.GET(baseURL+"/v2/auction_configurations", wrapper.GetAuctionConfigurationsV2)
	router.POST(baseURL+"/v2/auction_configurations", wrapper.CreateAuctionConfigurationV2)
	router.DELETE(baseURL+"/v2/auction_configurations/:id", wrapper.DeleteAuctionConfigurationV2)
	router.GET(baseURL+"/v2/auction_configurations/:id", wrapper.GetAuctionConfigurationV2)
	router.PATCH(baseURL+"/v2/auction_configurations/:id", wrapper.UpdateAuctionConfigurationV2)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rda2/bNvf/KgT/fbEBcpImw17knVtng7Feglw6/J+hMBiJtrlKlCZRabPC3/0BL6Io",
	"iZJoR5KzZ68aSxTP4bn9Di+H/Q79OEpiiinL4OV3mKAURZjhVPwiwTX/zf8McOanJGEkpvASzikgAYjX",
	"AIEUZ3Ge+hh6kPBXCWJb6EGKIgwvIQmgB1P8V05SHMBLlubYg5m/xRHivb5K8Rpewv87Lbk4lW+zUxLA",
	"3W7Hv86SmGZYcHSVpnF6o57wB35MGaaM/4mSJCQ+4iye/plxPr87ksK8V0mtMU7xDsS+n6cpDk4gb6S+",
	"E0SDGXtKBCuvSAAviwcnss2JYMSDrwpG4JaxJLs8FRzOVKM43ZwGKVqz0/Oz87PZ63PFGfQgpnkEL/+A",
	"D4hSnAohc+0wwggKhWy/ojTAAfzsQUZYyIU+D8Ad58mDkjWYsZTQDdx5EAUoYTidfcFPJsv64VBsN8VI",
	"8wikOElxhikjdAMUVfAFP2VgHafgEaUkzjOAAkAx+xqnXzJDACiI4gfoQRShvwVvXN3xI+F/PpAgQv6W",
	"UCx+bGIU8E/9LUrZQxxnjHPE8Dd/i+iGt9mgSIgyih8I/yONqbbiCDM+gogLepMKIfNmIV7nGX+fU8Ke",
	"JIHHL+rfnG5C/u4J0QB/q+pCjPI3/GRVR5IYakiSocSPwvDjGl7+0W32KElmSRonGdx53w0v/UO6bRIi",
	"to7TaCV+bfMI0ZVwaw8myP+CNrj4mWc4la1Qkqy4bX3emTJIEjXYWYAjRANOdU1CXBl77d30oqjS75IM",
	"H6X4Q36ykrajJOD7cU5Z9QeT7hgghoRxSDuIH/7EPoM1US1En9dKQla5zQLMEAk5R+0C1I2OLUkhQy5N",
	"nDIiw7iSS19cVv1I8c6Kj3Y1ue/VC/+am2vfR9wzeah3V9Wi0IldZdKcuvQlWgylLKu8uVE6oG7Nbhvo",
	"f7fFgL8RCYBsCVCWxT5BDAfgK2FbwLYkA3KAoLADEVTfYbphW3j52h4OnVkUvtRMTIKA8D9RCHgDC1u4",
	"yVVNxxa3duKov12SkgilTzPZPskfQuKvcofvRMtZLlKidgu8FiZmGY80NnvIOFKMsAQFF7cUbRz8suqK",
	"Ft8b09kUBjaNE+SU/JVjnvKIjIdbI5eFxRUMuLX6n3g/SzEK0EOIAW/I3bGjR1czrmC7lbZq4ULUzCH6",
	"jFw1fZZ3lLmIy+yiYjTt3pP7fPAzP6ZrsslTJEWhrcn2emJ/srHQlcCovE3nMSgoUpQ0zqnIaZOU+Hgd",
	"xnHak7FI2m9N0uCHBc/0fR53f2wVoS0kdbZ7AUK15TIqh39eMmGRYhHFHKVZD3LtjUYKe4FOFzploSbM",
	"e8L9vuBqj14fzIglBQSq+u3NUQy/aHR/zd8B8bKM7y1k8Dc/zDPyiN8TSiI+x5WLI1Hx80wTp3n0wGHv",
	"8KCovLqJSIo57fWE4UguBFV0KxMiSwfvSMa4QFUDPWrRodlf9TOZtgCZYDW/6lFBROhS9lu+RWmKnkpD",
	"qZK74f2C5aK/a0YiHOfMgnvyRZVVQCiISBiSDPuxFKBWX9m7WEhQaUsjEheSLUl/tkBQx4htne4f3jvC",
	"kMDFagxyBcnZ47mw02Og3+O5CwBqwZjy6AvM+4z/nwhyXG1HwLlOMZbodjS0ClY5JXwO3REHUcBzfAaW",
	"i0o07ce3ehjbBxsfSBDw+NXKlWpQxFtXzszFYguLjqAwMFX8jeGUonD1ldAVjRlZqzV/CyO/bzHb4hQU",
	"34CvhILKNwClGGDK51BB6dYPcRxiRA/JO0i2CvAa5aEFQ5Y04HRxBshaLpCQTK1IiC8aOUKTnSKt2StJ",
	"mTTVyPAmwnssNWWYMUI3yimL1Ztr01mb2zIgQgm3sIrAgO7KEp97gf0RhTm2ADqfkiImYfziHFpRvRc+",
	"bRyJdbPU2IZRD6YFAEW0CysrK/8oTLZodb7y46D8eSF/ds4T36rhliOvz1gqj0eao5jcW9c2lrcfwcXr",
	"n3+evQai8ewc8MY67yu0xgMRihIxtPtbnvihb4VHnlfSzHPbQqcpNjc+Llz4mFcZuagwcjHsMpOVA0oY",
	"DsAt41GuP9veL7juGsbU6lvVJX9tYZXH0/pZdSuja9etjLt110uI3FvrcjM5s7rVex32LRS7RIrXx5SM",
	"YsFZQuXWY7HH1tySI9mqSJFE/pAidxnO65tOdUab+X13uxcgXEtyP/6GmsPKvUXu5tygy1B6hD8ipBy2",
	"VyStsGv7ilCZefDEpgj6lYS62Hqzxb8DstbWSUSZtX5V6XQxnSBZkTorDsstvzYWjVT20ASzf0+yS1Q9",
	"iHTY7oHFcN2gqdt6R92jIvY9Ki7H+fVSbFF1bJ6Wp2W65fmM/GJPSpPtvpp41IrPFsNotQh5+kzbgPg5",
	"jtY1pepjexYqjtoBlefXJz0ejHCWoU3rd8XrhqZqElT9F82buFxrL4dgiFiQ64iBQqYkGOlgG0jijDDy",
	"yGeOQjR6lblcBVaMihdNOYaE4hlhOCq51Y+mzRU02UPTU7Xa/ECClVx7MBdY1Ty6+4CUsgaHHO0doXjJ",
	"pWaK0JKMNd8dSagjnIIaZEW2EKSZaZVC03mKik3852ACtK72rFGYYQ/GFCvpNtZt1SqsLXsqFl/BDzwh",
	"mQdR/OCB/xeHMn/sDUVG15Y9mDojxbqQhQlt6sXZ1TfzDx+ubqAH399cvYUeXH64u7q5vVveLefvoAc/",
	"LRdXH6EHb65+n98srhYG+RLfsjBmqzy3jfs2jBm4v9fDFidk+8db9qi902Hcf8cUW6X/n5jiUvTqcG4/",
	"F0V/DqQFw60CKEi/IZt4HmQe+PTbPMgcxdDGQKeNNiwzjH19OKRhFcVLyeVbfTb5R9u5mQgHpKWrj4ma",
	"Ieg2QJ/ad7FxzaSDxJMQ+dhYzq1tdxdvtezfY4Y8cE8Je5IqEAejPfBeHKD+Jc9wvz4qNF2sImmzisSw",
	"isXdlTr+7WARSexKnNCMIerbPWKpXmomlmlMZTLYz4TZ8xiaKo63W82vNcTem/G1q48upZb9d0L8lcCe",
	"ChzVpku1F//Qs7MO52JHPVpT5mtWblUuy2f96miL2F2qrPuenZy9NvdKAuyTSJRONMbSvuStDkdWlrm5",
	"hoFInyxdlcmJU1aLC3tqg27OhHynzwgFBopDrwTyd1fzxdXNm4/zm0UJ6/PF/Ppu+enKit/PmAmbQngp",
	"s+B6+tg6uzWPdWrHNR4OXShFYs4GokEaVwJMZXO0kEDJkH422URRkQTLhQe42mcxDZ9qc0f+/CN/rHZs",
	"C6lfy29bppSGqsoB6mdDDVA7u0ohmxmr3AkueVAPpp2AKaLOc1o1mzXV58E1CUVNJDez4qyACrGdEHar",
	"RFBKwzJFrb85inzGOvCjJGDOLqsaaYhh5JP5zvUlpv/aArbxpAjUhSx7w3RhRX1HRHSXxlq7dTG9MNBG",
	"h7/IF0AUx+IAsLjGacuJz3agMpFJku0fL+8ZsbYMo3gL8gyLM5X7dN2fZrn2JE6AyKzefmqVdyobHcSp",
	"+yFOtRqmQpEWnmZxzyOiQ52ermvf2dwHWWu3BuZGOC5doRmEWnMUvX8pAhH/NW0M5hS7AApHiITdSHOf",
	"Sew3uqoMaMywKtkz1sTUkyFPfPDxteiPNyN0HfOey7LriFAwv15yp8FpJg347OT1yZmKRxQlBF7Ci5Oz",
	"kwtR0cy2YjAc01ZqU1eVCIrnGywyGemMJKZLLtlfMasX4WWwdmXB+dnZXhcVuB2S7KgJbhyatNxrAMLi",
	"wGqS1AoiM4l++gyjjQ09wNPqhQzicoQ84goszoHaCHiQoU3GzXtuefuZR4w4s4j7bYoRw40aaRkncMbe",
	"xMHTYJdC2AqZqzGJ5+S7hrZf83/qPD7nyoqTDpYqDm2/wKKpALgbSsNSITYSfSreeVZPO/1Ogp1EnhAz",
	"3DSBhXhuNYGKFn6yrME2GAGSSgCy3Pdxlq3zMHwazPwlq4cIx3OONs8NNgfHGGdTG0iYv2J2mCTNG21a",
	"YLhsclrceMOhNUHM3za1cJ8ExwxCRZ7gEorO/kWhSKrlGaGoD+WnBPYDkXx46K5htRM4j+cKewDwsCRt",
	"lgyHB9GmsAvbdMfFPaBwEuyzGVCHl40PaH0INjRkWT1oNFAaEYf2BZ5/kAuW4NHigrKwZ1WpN+oGDEsp",
	"0EQI0n3Xwn6YYitez6xYYW9pSNPeoBdP7PW3o9i4/cKHiSGnnYmmB1ivFhgallruL+jVa7vfuIJZm+p7",
	"0c3G0jR4d6iwvL0Cyagg2RM+jmCJAkgPl+xYYHvkyHQkPH4x8anA7OfEJ1nDSLpXeN/qRlPAt1/Wybrj",
	"dDmOQSeAvjHyQp6lNPqg+60uEB3DJ7ScpsXnCtm6OgzdDQnBZaWtTQkVO3aEVlM1fWiq2k6Cn90j9Xpc",
	"9GlMXJxU8Rzx+mQxEqxN4rXHwa5JVajgqd93qwWk6kxoJyBZyg2nwaaeCui9IMtaoDkwfrXQKHWxsDfo",
	"QzZbgfg4/tJS+zMt5nUwUdeuvex2YDxsrTHu02q7uzniZpvi+zDUytEkiHqwrLx9ws+YwNsXdKY3Q47O",
	"z5DrSMB95KB0HEh/ecahcH+4GOWcChwhB3gG5I8J9a0Qvx+0T+I+e7jNSIju4CWjIniXsprecABSHwDR",
	"k0Nzt8W6uP9kGDylvTSgtsezx4fWlxYU/geUbIPMvqAQEopXGrDa/KOoThM3Hldtw1YmAR6eQJ4Vl3iI",
	"/87srxyL2bv6/8zK68ZKmZo3RP78k/WGyHZyKEnaqekz7UMRC4AqLbBS03d1lORSvH5VPfdl+e/Nummq",
	"yU77IM37QIYaqCLaNdrqzSMl4UYhczsZfa8uQyzPWghVbp9rkNE1PDwIjZ+9Wa5K2SuF06WoA6dvRr+l",
	"478rH/albfo6mHGis3GLy7SJWo1wUy1FZfDACVql7tqmjmoMdkzKKlrqS8g0uUmSsd4Be70gM2YCZvPb",
	"aQyCZ2AOwhkp85rKr4+TcU3u3SrTcvJuVd3XmV/dFm2mwK5GBfVeyKWHMyhuZaUACkFqmfRh1q0unxzD",
	"tHVd97SAVSFb10VZaz4oWJV1qBYdmKbsCFOmYvpQSrWdBKM6x+n1OemY8NR0zSnUz6GpRyYjwdIkrnsc",
	"TJrUgRUe9Town3Z3AtF9Jq/nGB+FclVo7Y48kvlBYSdXwy3EJYffBziiRnwck1W3e08KNSXNxn+zqXQ0",
	"JMjkUnh1iWvrPJU3JrSeUMrTFFOmVTCS97bJRJEfVjLilJLZcZd43KDXLh8L7vKGk4Buy8C8zlB0DBXP",
	"h1du69hHgtWRA9RxAHUifSko7fDDx/Oh6pg+nR+xksn8P/UmLWYCYtgj1DMpcU5VN/B4/iKKmjQfL6iu",
	"yVHFnd70jOomm1/9G+ubnh9fnhlWXlKRk3vYma7OafKI9YKKnY4Vt7rqnVzjlrh9MX0sTCRPQ3gJT1FC",
	"4O7z7r8BAAD//xMzZGIMjAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
