// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateAppJSONBodyPlatformId.
const (
	CreateAppJSONBodyPlatformIdAndroid CreateAppJSONBodyPlatformId = "android"
	CreateAppJSONBodyPlatformIdIos     CreateAppJSONBodyPlatformId = "ios"
)

// Defines values for UpdateAppJSONBodyPlatformId.
const (
	UpdateAppJSONBodyPlatformIdAndroid UpdateAppJSONBodyPlatformId = "android"
	UpdateAppJSONBodyPlatformIdIos     UpdateAppJSONBodyPlatformId = "ios"
)

// Defines values for CreateAuctionConfigurationJSONBodyAdType.
const (
	CreateAuctionConfigurationJSONBodyAdTypeBanner       CreateAuctionConfigurationJSONBodyAdType = "banner"
	CreateAuctionConfigurationJSONBodyAdTypeInterstitial CreateAuctionConfigurationJSONBodyAdType = "interstitial"
	CreateAuctionConfigurationJSONBodyAdTypeRewarded     CreateAuctionConfigurationJSONBodyAdType = "rewarded"
)

// Defines values for UpdateAuctionConfigurationJSONBodyAdType.
const (
	UpdateAuctionConfigurationJSONBodyAdTypeBanner       UpdateAuctionConfigurationJSONBodyAdType = "banner"
	UpdateAuctionConfigurationJSONBodyAdTypeInterstitial UpdateAuctionConfigurationJSONBodyAdType = "interstitial"
	UpdateAuctionConfigurationJSONBodyAdTypeRewarded     UpdateAuctionConfigurationJSONBodyAdType = "rewarded"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyAdType.
const (
	CreateAuctionConfigurationV2JSONBodyAdTypeBanner       CreateAuctionConfigurationV2JSONBodyAdType = "banner"
	CreateAuctionConfigurationV2JSONBodyAdTypeInterstitial CreateAuctionConfigurationV2JSONBodyAdType = "interstitial"
	CreateAuctionConfigurationV2JSONBodyAdTypeRewarded     CreateAuctionConfigurationV2JSONBodyAdType = "rewarded"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyBidding.
const (
	CreateAuctionConfigurationV2JSONBodyBiddingAdmob      CreateAuctionConfigurationV2JSONBodyBidding = "admob"
	CreateAuctionConfigurationV2JSONBodyBiddingAmazon     CreateAuctionConfigurationV2JSONBodyBidding = "amazon"
	CreateAuctionConfigurationV2JSONBodyBiddingApplovin   CreateAuctionConfigurationV2JSONBodyBidding = "applovin"
	CreateAuctionConfigurationV2JSONBodyBiddingBidmachine CreateAuctionConfigurationV2JSONBodyBidding = "bidmachine"
	CreateAuctionConfigurationV2JSONBodyBiddingBigoads    CreateAuctionConfigurationV2JSONBodyBidding = "bigoads"
	CreateAuctionConfigurationV2JSONBodyBiddingChartboost CreateAuctionConfigurationV2JSONBodyBidding = "chartboost"
	CreateAuctionConfigurationV2JSONBodyBiddingDtexchange CreateAuctionConfigurationV2JSONBodyBidding = "dtexchange"
	CreateAuctionConfigurationV2JSONBodyBiddingGam        CreateAuctionConfigurationV2JSONBodyBidding = "gam"
	CreateAuctionConfigurationV2JSONBodyBiddingInmobi     CreateAuctionConfigurationV2JSONBodyBidding = "inmobi"
	CreateAuctionConfigurationV2JSONBodyBiddingIronsource CreateAuctionConfigurationV2JSONBodyBidding = "ironsource"
	CreateAuctionConfigurationV2JSONBodyBiddingMeta       CreateAuctionConfigurationV2JSONBodyBidding = "meta"
	CreateAuctionConfigurationV2JSONBodyBiddingMintegral  CreateAuctionConfigurationV2JSONBodyBidding = "mintegral"
	CreateAuctionConfigurationV2JSONBodyBiddingMobilefuse CreateAuctionConfigurationV2JSONBodyBidding = "mobilefuse"
	CreateAuctionConfigurationV2JSONBodyBiddingUnityads   CreateAuctionConfigurationV2JSONBodyBidding = "unityads"
	CreateAuctionConfigurationV2JSONBodyBiddingVkads      CreateAuctionConfigurationV2JSONBodyBidding = "vkads"
	CreateAuctionConfigurationV2JSONBodyBiddingVungle     CreateAuctionConfigurationV2JSONBodyBidding = "vungle"
	CreateAuctionConfigurationV2JSONBodyBiddingYandex     CreateAuctionConfigurationV2JSONBodyBidding = "yandex"
)

// Defines values for CreateAuctionConfigurationV2JSONBodyDemands.
const (
	CreateAuctionConfigurationV2JSONBodyDemandsAdmob      CreateAuctionConfigurationV2JSONBodyDemands = "admob"
	CreateAuctionConfigurationV2JSONBodyDemandsAmazon     CreateAuctionConfigurationV2JSONBodyDemands = "amazon"
	CreateAuctionConfigurationV2JSONBodyDemandsApplovin   CreateAuctionConfigurationV2JSONBodyDemands = "applovin"
	CreateAuctionConfigurationV2JSONBodyDemandsBidmachine CreateAuctionConfigurationV2JSONBodyDemands = "bidmachine"
	CreateAuctionConfigurationV2JSONBodyDemandsBigoads    CreateAuctionConfigurationV2JSONBodyDemands = "bigoads"
	CreateAuctionConfigurationV2JSONBodyDemandsChartboost CreateAuctionConfigurationV2JSONBodyDemands = "chartboost"
	CreateAuctionConfigurationV2JSONBodyDemandsDtexchange CreateAuctionConfigurationV2JSONBodyDemands = "dtexchange"
	CreateAuctionConfigurationV2JSONBodyDemandsGam        CreateAuctionConfigurationV2JSONBodyDemands = "gam"
	CreateAuctionConfigurationV2JSONBodyDemandsInmobi     CreateAuctionConfigurationV2JSONBodyDemands = "inmobi"
	CreateAuctionConfigurationV2JSONBodyDemandsIronsource CreateAuctionConfigurationV2JSONBodyDemands = "ironsource"
	CreateAuctionConfigurationV2JSONBodyDemandsMeta       CreateAuctionConfigurationV2JSONBodyDemands = "meta"
	CreateAuctionConfigurationV2JSONBodyDemandsMintegral  CreateAuctionConfigurationV2JSONBodyDemands = "mintegral"
	CreateAuctionConfigurationV2JSONBodyDemandsMobilefuse CreateAuctionConfigurationV2JSONBodyDemands = "mobilefuse"
	CreateAuctionConfigurationV2JSONBodyDemandsUnityads   CreateAuctionConfigurationV2JSONBodyDemands = "unityads"
	CreateAuctionConfigurationV2JSONBodyDemandsVkads      CreateAuctionConfigurationV2JSONBodyDemands = "vkads"
	CreateAuctionConfigurationV2JSONBodyDemandsVungle     CreateAuctionConfigurationV2JSONBodyDemands = "vungle"
	CreateAuctionConfigurationV2JSONBodyDemandsYandex     CreateAuctionConfigurationV2JSONBodyDemands = "yandex"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyAdType.
const (
	UpdateAuctionConfigurationV2JSONBodyAdTypeBanner       UpdateAuctionConfigurationV2JSONBodyAdType = "banner"
	UpdateAuctionConfigurationV2JSONBodyAdTypeInterstitial UpdateAuctionConfigurationV2JSONBodyAdType = "interstitial"
	UpdateAuctionConfigurationV2JSONBodyAdTypeRewarded     UpdateAuctionConfigurationV2JSONBodyAdType = "rewarded"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyBidding.
const (
	UpdateAuctionConfigurationV2JSONBodyBiddingAdmob      UpdateAuctionConfigurationV2JSONBodyBidding = "admob"
	UpdateAuctionConfigurationV2JSONBodyBiddingAmazon     UpdateAuctionConfigurationV2JSONBodyBidding = "amazon"
	UpdateAuctionConfigurationV2JSONBodyBiddingApplovin   UpdateAuctionConfigurationV2JSONBodyBidding = "applovin"
	UpdateAuctionConfigurationV2JSONBodyBiddingBidmachine UpdateAuctionConfigurationV2JSONBodyBidding = "bidmachine"
	UpdateAuctionConfigurationV2JSONBodyBiddingBigoads    UpdateAuctionConfigurationV2JSONBodyBidding = "bigoads"
	UpdateAuctionConfigurationV2JSONBodyBiddingChartboost UpdateAuctionConfigurationV2JSONBodyBidding = "chartboost"
	UpdateAuctionConfigurationV2JSONBodyBiddingDtexchange UpdateAuctionConfigurationV2JSONBodyBidding = "dtexchange"
	UpdateAuctionConfigurationV2JSONBodyBiddingGam        UpdateAuctionConfigurationV2JSONBodyBidding = "gam"
	UpdateAuctionConfigurationV2JSONBodyBiddingInmobi     UpdateAuctionConfigurationV2JSONBodyBidding = "inmobi"
	UpdateAuctionConfigurationV2JSONBodyBiddingIronsource UpdateAuctionConfigurationV2JSONBodyBidding = "ironsource"
	UpdateAuctionConfigurationV2JSONBodyBiddingMeta       UpdateAuctionConfigurationV2JSONBodyBidding = "meta"
	UpdateAuctionConfigurationV2JSONBodyBiddingMintegral  UpdateAuctionConfigurationV2JSONBodyBidding = "mintegral"
	UpdateAuctionConfigurationV2JSONBodyBiddingMobilefuse UpdateAuctionConfigurationV2JSONBodyBidding = "mobilefuse"
	UpdateAuctionConfigurationV2JSONBodyBiddingUnityads   UpdateAuctionConfigurationV2JSONBodyBidding = "unityads"
	UpdateAuctionConfigurationV2JSONBodyBiddingVkads      UpdateAuctionConfigurationV2JSONBodyBidding = "vkads"
	UpdateAuctionConfigurationV2JSONBodyBiddingVungle     UpdateAuctionConfigurationV2JSONBodyBidding = "vungle"
	UpdateAuctionConfigurationV2JSONBodyBiddingYandex     UpdateAuctionConfigurationV2JSONBodyBidding = "yandex"
)

// Defines values for UpdateAuctionConfigurationV2JSONBodyDemands.
const (
	UpdateAuctionConfigurationV2JSONBodyDemandsAdmob      UpdateAuctionConfigurationV2JSONBodyDemands = "admob"
	UpdateAuctionConfigurationV2JSONBodyDemandsAmazon     UpdateAuctionConfigurationV2JSONBodyDemands = "amazon"
	UpdateAuctionConfigurationV2JSONBodyDemandsApplovin   UpdateAuctionConfigurationV2JSONBodyDemands = "applovin"
	UpdateAuctionConfigurationV2JSONBodyDemandsBidmachine UpdateAuctionConfigurationV2JSONBodyDemands = "bidmachine"
	UpdateAuctionConfigurationV2JSONBodyDemandsBigoads    UpdateAuctionConfigurationV2JSONBodyDemands = "bigoads"
	UpdateAuctionConfigurationV2JSONBodyDemandsChartboost UpdateAuctionConfigurationV2JSONBodyDemands = "chartboost"
	UpdateAuctionConfigurationV2JSONBodyDemandsDtexchange UpdateAuctionConfigurationV2JSONBodyDemands = "dtexchange"
	UpdateAuctionConfigurationV2JSONBodyDemandsGam        UpdateAuctionConfigurationV2JSONBodyDemands = "gam"
	UpdateAuctionConfigurationV2JSONBodyDemandsInmobi     UpdateAuctionConfigurationV2JSONBodyDemands = "inmobi"
	UpdateAuctionConfigurationV2JSONBodyDemandsIronsource UpdateAuctionConfigurationV2JSONBodyDemands = "ironsource"
	UpdateAuctionConfigurationV2JSONBodyDemandsMeta       UpdateAuctionConfigurationV2JSONBodyDemands = "meta"
	UpdateAuctionConfigurationV2JSONBodyDemandsMintegral  UpdateAuctionConfigurationV2JSONBodyDemands = "mintegral"
	UpdateAuctionConfigurationV2JSONBodyDemandsMobilefuse UpdateAuctionConfigurationV2JSONBodyDemands = "mobilefuse"
	UpdateAuctionConfigurationV2JSONBodyDemandsUnityads   UpdateAuctionConfigurationV2JSONBodyDemands = "unityads"
	UpdateAuctionConfigurationV2JSONBodyDemandsVkads      UpdateAuctionConfigurationV2JSONBodyDemands = "vkads"
	UpdateAuctionConfigurationV2JSONBodyDemandsVungle     UpdateAuctionConfigurationV2JSONBodyDemands = "vungle"
	UpdateAuctionConfigurationV2JSONBodyDemandsYandex     UpdateAuctionConfigurationV2JSONBodyDemands = "yandex"
)

// IdParam A positive integer ID
type IdParam = int

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Error code
		Code int `json:"code"`

		// Message Error message
		Message string `json:"message"`
	} `json:"error"`
}

// CreateAppJSONBody defines parameters for CreateApp.
type CreateAppJSONBody struct {
	// AppKey A unique key for the app
	AppKey string `json:"app_key"`

	// HumanName The human-readable name of the app
	HumanName string `json:"human_name"`

	// Id A positive integer ID
	Id int `json:"id"`

	// PackageName The package name of the app
	PackageName string                      `json:"package_name"`
	PlatformId  CreateAppJSONBodyPlatformId `json:"platform_id"`
	PublicUid   *openapi_types.UUID         `json:"public_uid,omitempty"`

	// UserId A positive integer ID
	UserId int `json:"user_id"`
}

// CreateAppJSONBodyPlatformId defines parameters for CreateApp.
type CreateAppJSONBodyPlatformId string

// UpdateAppJSONBody defines parameters for UpdateApp.
type UpdateAppJSONBody struct {
	// AppKey A unique key for the app
	AppKey *string `json:"app_key,omitempty"`

	// HumanName The human-readable name of the app
	HumanName *string `json:"human_name,omitempty"`

	// Id A positive integer ID
	Id *int `json:"id,omitempty"`

	// PackageName The package name of the app
	PackageName *string                      `json:"package_name,omitempty"`
	PlatformId  *UpdateAppJSONBodyPlatformId `json:"platform_id,omitempty"`
	PublicUid   *openapi_types.UUID          `json:"public_uid,omitempty"`

	// UserId A positive integer ID
	UserId *int `json:"user_id,omitempty"`
}

// UpdateAppJSONBodyPlatformId defines parameters for UpdateApp.
type UpdateAppJSONBodyPlatformId string

// CreateAuctionConfigurationJSONBody defines parameters for CreateAuctionConfiguration.
type CreateAuctionConfigurationJSONBody struct {
	AdType CreateAuctionConfigurationJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name Name of the auction configuration
	Name string `json:"name"`

	// Pricefloor Price floor for the auction configuration
	Pricefloor float32 `json:"pricefloor"`

	// Rounds Auction rounds
	Rounds []struct {
		// Demands List of demands for the round
		Demands []string `json:"demands"`

		// Id Round ID
		Id string `json:"id"`

		// Timeout Timeout for the round in milliseconds
		Timeout int `json:"timeout"`
	} `json:"rounds"`
}

// CreateAuctionConfigurationJSONBodyAdType defines parameters for CreateAuctionConfiguration.
type CreateAuctionConfigurationJSONBodyAdType string

// UpdateAuctionConfigurationJSONBody defines parameters for UpdateAuctionConfiguration.
type UpdateAuctionConfigurationJSONBody struct {
	AdType UpdateAuctionConfigurationJSONBodyAdType `json:"ad_type"`

	// AppId A positive integer ID
	AppId int `json:"app_id"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// Name Name of the auction configuration
	Name string `json:"name"`

	// Pricefloor Price floor for the auction configuration
	Pricefloor float32 `json:"pricefloor"`

	// Rounds Auction rounds
	Rounds []struct {
		// Demands List of demands for the round
		Demands []string `json:"demands"`

		// Id Round ID
		Id string `json:"id"`

		// Timeout Timeout for the round in milliseconds
		Timeout int `json:"timeout"`
	} `json:"rounds"`
}

// UpdateAuctionConfigurationJSONBodyAdType defines parameters for UpdateAuctionConfiguration.
type UpdateAuctionConfigurationJSONBodyAdType string

// CreateAuctionConfigurationV2JSONBody defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBody struct {
	AdType CreateAuctionConfigurationV2JSONBodyAdType `json:"ad_type"`

	// AdUnitIds List of ad unit IDs
	AdUnitIds *[]int `json:"ad_unit_ids,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Bidding List of bidding sources
	Bidding *[]CreateAuctionConfigurationV2JSONBodyBidding `json:"bidding,omitempty"`

	// Demands List of demand sources
	Demands *[]CreateAuctionConfigurationV2JSONBodyDemands `json:"demands,omitempty"`

	// ExternalWinNotifications Whether external win notifications are enabled
	ExternalWinNotifications *bool `json:"external_win_notifications,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsDefault Indicates if this is the default configuration
	IsDefault  *bool   `json:"is_default,omitempty"`
	Name       string  `json:"name"`
	Pricefloor float32 `json:"pricefloor"`

	// SegmentId A positive integer ID
	SegmentId *int `json:"segment_id,omitempty"`

	// Settings A map of configuration settings
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// Timeout Timeout value in milliseconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// CreateAuctionConfigurationV2JSONBodyAdType defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyAdType string

// CreateAuctionConfigurationV2JSONBodyBidding defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyBidding string

// CreateAuctionConfigurationV2JSONBodyDemands defines parameters for CreateAuctionConfigurationV2.
type CreateAuctionConfigurationV2JSONBodyDemands string

// UpdateAuctionConfigurationV2JSONBody defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBody struct {
	AdType *UpdateAuctionConfigurationV2JSONBodyAdType `json:"ad_type,omitempty"`

	// AdUnitIds List of ad unit IDs
	AdUnitIds *[]int `json:"ad_unit_ids,omitempty"`

	// AppId A positive integer ID
	AppId *int `json:"app_id,omitempty"`

	// Bidding List of bidding sources
	Bidding *[]UpdateAuctionConfigurationV2JSONBodyBidding `json:"bidding,omitempty"`

	// Demands List of demand sources
	Demands *[]UpdateAuctionConfigurationV2JSONBodyDemands `json:"demands,omitempty"`

	// ExternalWinNotifications Whether external win notifications are enabled
	ExternalWinNotifications *bool `json:"external_win_notifications,omitempty"`

	// Id A positive integer primary ID, read-only
	Id *int `json:"id,omitempty"`

	// IsDefault Indicates if this is the default configuration
	IsDefault  *bool    `json:"is_default,omitempty"`
	Name       *string  `json:"name,omitempty"`
	Pricefloor *float32 `json:"pricefloor,omitempty"`

	// SegmentId A positive integer ID
	SegmentId *int `json:"segment_id,omitempty"`

	// Settings A map of configuration settings
	Settings *map[string]interface{} `json:"settings,omitempty"`

	// Timeout Timeout value in milliseconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// UpdateAuctionConfigurationV2JSONBodyAdType defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyAdType string

// UpdateAuctionConfigurationV2JSONBodyBidding defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyBidding string

// UpdateAuctionConfigurationV2JSONBodyDemands defines parameters for UpdateAuctionConfigurationV2.
type UpdateAuctionConfigurationV2JSONBodyDemands string

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody CreateAppJSONBody

// UpdateAppJSONRequestBody defines body for UpdateApp for application/json ContentType.
type UpdateAppJSONRequestBody UpdateAppJSONBody

// CreateAuctionConfigurationJSONRequestBody defines body for CreateAuctionConfiguration for application/json ContentType.
type CreateAuctionConfigurationJSONRequestBody CreateAuctionConfigurationJSONBody

// UpdateAuctionConfigurationJSONRequestBody defines body for UpdateAuctionConfiguration for application/json ContentType.
type UpdateAuctionConfigurationJSONRequestBody UpdateAuctionConfigurationJSONBody

// CreateAuctionConfigurationV2JSONRequestBody defines body for CreateAuctionConfigurationV2 for application/json ContentType.
type CreateAuctionConfigurationV2JSONRequestBody CreateAuctionConfigurationV2JSONBody

// UpdateAuctionConfigurationV2JSONRequestBody defines body for UpdateAuctionConfigurationV2 for application/json ContentType.
type UpdateAuctionConfigurationV2JSONRequestBody UpdateAuctionConfigurationV2JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List apps
	// (GET /apps)
	GetApps(ctx echo.Context) error
	// Create app
	// (POST /apps)
	CreateApp(ctx echo.Context) error
	// Delete app
	// (DELETE /apps/{id})
	DeleteApp(ctx echo.Context, id IdParam) error
	// Get app
	// (GET /apps/{id})
	GetApp(ctx echo.Context, id IdParam) error
	// Update app
	// (PATCH /apps/{id})
	UpdateApp(ctx echo.Context, id IdParam) error
	// List auction configurations
	// (GET /auction_configurations)
	GetAuctionConfigurations(ctx echo.Context) error
	// Create auction configuration
	// (POST /auction_configurations)
	CreateAuctionConfiguration(ctx echo.Context) error
	// Delete auction configuration
	// (DELETE /auction_configurations/{id})
	DeleteAuctionConfiguration(ctx echo.Context, id IdParam) error
	// Get auction configuration
	// (GET /auction_configurations/{id})
	GetAuctionConfiguration(ctx echo.Context, id IdParam) error
	// Update auction configuration
	// (PATCH /auction_configurations/{id})
	UpdateAuctionConfiguration(ctx echo.Context, id IdParam) error
	// List auction configurations V2
	// (GET /v2/auction_configurations)
	GetAuctionConfigurationsV2(ctx echo.Context) error
	// Create auction configuration V2
	// (POST /v2/auction_configurations)
	CreateAuctionConfigurationV2(ctx echo.Context) error
	// Delete auction configuration
	// (DELETE /v2/auction_configurations/{id})
	DeleteAuctionConfigurationV2(ctx echo.Context, id IdParam) error
	// Get auction configuration V2
	// (GET /v2/auction_configurations/{id})
	GetAuctionConfigurationV2(ctx echo.Context, id IdParam) error
	// Update auction configuration V2
	// (PATCH /v2/auction_configurations/{id})
	UpdateAuctionConfigurationV2(ctx echo.Context, id IdParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApps converts echo context to params.
func (w *ServerInterfaceWrapper) GetApps(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApps(ctx)
	return err
}

// CreateApp converts echo context to params.
func (w *ServerInterfaceWrapper) CreateApp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateApp(ctx)
	return err
}

// DeleteApp converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApp(ctx, id)
	return err
}

// GetApp converts echo context to params.
func (w *ServerInterfaceWrapper) GetApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApp(ctx, id)
	return err
}

// UpdateApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateApp(ctx, id)
	return err
}

// GetAuctionConfigurations converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurations(ctx)
	return err
}

// CreateAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuctionConfiguration(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuctionConfiguration(ctx)
	return err
}

// DeleteAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuctionConfiguration(ctx, id)
	return err
}

// GetAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfiguration(ctx, id)
	return err
}

// UpdateAuctionConfiguration converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuctionConfiguration(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuctionConfiguration(ctx, id)
	return err
}

// GetAuctionConfigurationsV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurationsV2(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurationsV2(ctx)
	return err
}

// CreateAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuctionConfigurationV2(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuctionConfigurationV2(ctx)
	return err
}

// DeleteAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuctionConfigurationV2(ctx, id)
	return err
}

// GetAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuctionConfigurationV2(ctx, id)
	return err
}

// UpdateAuctionConfigurationV2 converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuctionConfigurationV2(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuctionConfigurationV2(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/apps", wrapper.GetApps)
	router.POST(baseURL+"/apps", wrapper.CreateApp)
	router.DELETE(baseURL+"/apps/:id", wrapper.DeleteApp)
	router.GET(baseURL+"/apps/:id", wrapper.GetApp)
	router.PATCH(baseURL+"/apps/:id", wrapper.UpdateApp)
	router.GET(baseURL+"/auction_configurations", wrapper.GetAuctionConfigurations)
	router.POST(baseURL+"/auction_configurations", wrapper.CreateAuctionConfiguration)
	router.DELETE(baseURL+"/auction_configurations/:id", wrapper.DeleteAuctionConfiguration)
	router.GET(baseURL+"/auction_configurations/:id", wrapper.GetAuctionConfiguration)
	router.PATCH(baseURL+"/auction_configurations/:id", wrapper.UpdateAuctionConfiguration)
	router.GET(baseURL+"/v2/auction_configurations", wrapper.GetAuctionConfigurationsV2)
	router.POST(baseURL+"/v2/auction_configurations", wrapper.CreateAuctionConfigurationV2)
	router.DELETE(baseURL+"/v2/auction_configurations/:id", wrapper.DeleteAuctionConfigurationV2)
	router.GET(baseURL+"/v2/auction_configurations/:id", wrapper.GetAuctionConfigurationV2)
	router.PATCH(baseURL+"/v2/auction_configurations/:id", wrapper.UpdateAuctionConfigurationV2)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZ32/juBH+Vwh2H1pAjr3ePvktvRSHoNdecLhrHxaBQYtjmxeJ5JGUN27g/70YUpIl",
	"i7aVxD+y6JMtkiJnPs5834h8oanKtZIgnaWTF6qZYTk4MP5J8Ad8xr8cbGqEdkJJOqG3kghO1JwwYsCq",
	"wqRAEyqwSzO3pAmVLAc6oYLThBr4oxAGOJ04U0BCbbqEnOGsnwzM6YT+abi1Yhh67VBwutls8G2rlbTg",
	"Lfq7Mcr8UrZgQ6qkA+nwL9M6EylDE4e/W7TzpedSgLOG1Tp++j6i0rQwBvgNxUHle35RPnBr7U35JDid",
	"VA03YcyNNyShnypD6NI5bSdDb+GgHKTMYsgNm7vheDQeDT6PS8toQkEWOZ18pTMmJRgPMu6OE06wzGP7",
	"jRkOnD4m1AmXIei3nPyKNiU0mEatM0Iu6CahjDPtwAyeYN00uW48ldldGGWREwPagAXphFyQclXyBGtL",
	"5sqQFTNCFZYwTiS4b8o82QYAjOdqRhPKcvZfbxtut1oJ/DsTPGfpUkjwDwvFOL6aLplxM6WsQ4scPKdL",
	"Jhc4ZsFyD2WuZgL/GCXrKM7BoQc5Ar0wHmQclsG8sNhfSOHWYYHVU/lbyEWGfWsmOTy398J7+Q9YR7dD",
	"68Y2aH0q+FmW/Tynk6+Hw55pPdBGaUs3yUsjS7+GtNUZc3Nl8ql/WhY5k1Of1gnVLH1iC6geCwsmjGJa",
	"TzG2HjdNDLQunR1wcExkuEjD67r14u57xxECME4EhkFfjvGFH4NEUG6omv0OqaM7Pt9Vvpa+B6hbjvum",
	"U3nd9qPaiS53k0KKPwrAxPN555ZAEItIfDY2vTPPr0sgvn9ggHE2y4DgQFSFAzMK3of3dyIsunY5os+i",
	"zUg+sno1dFCaUcwykU6L8CJ2MEcntCh8tHcWqhKhj7S1YuXBx0YnoBLKihR9HqRKzsWiMCwgUAdRrPvC",
	"aRQz4RCvlKSBARo4g09dkCujCukJVRuRwjxTyngu3Z9lYe0fmkuTP9+hzKTMAf/LXghjTHRw3AcANcJW",
	"lYAco7nNa1GsyKsnmrvctn/QmdiujKFjWJTV2qYOv15k1IM2jMiZWZesESetfzWJKgBE2vvrq46fQC7c",
	"kk4+x4hsmxed6R+wj/jOLa3vWQae06ywYgX/FFLkWGCFyjyvHkf14rLIZ6h2dXZ2BaVcpM5e4SAPXxOt",
	"PeKQs+gEPwnrEJhyQG29n7A5X/u1Oz+chMKt+9YRKHMh78O8215mDFtvN7y93C84L7m/Oz61EzmowkVk",
	"K3S0TSVCklxkmbCQqgBgvQ3b2X01WlYdHUatkN0u/RiRkgMexyZ9PU0foBOvb20u6St2g9XYZ981VGw1",
	"7iNkNTBNPI4R7Gv8/x7FCrftCnp1EMatSl1NdfgUvx+n4hAPMo4luiP3dy02Pa5TuzT2Go2bCc6Rv/Za",
	"VQ6o+LavZc0Th4iJPUXhxKvCswMjWTb9JuRUKifm5cFRxJD/LMEtwZDqHfJNSNJ6hzADBCR+AjW+CmZK",
	"ZcDkW+oHYacc5qzIIhpyLzmuC5YILCWEJcJ6MSnf6Gh915yqPHlVsfGmksHCIgfpegehBeeEXJTJxQW6",
	"wLKHZtJ1z+hIzjRGSstxUk8V4dmjAr1iWQERYa4/AIV0X8Y0qs5HZTBmUTiBrNndP56nUq5XajenikdK",
	"Vn/cSnxf19eE5mAtW+x9r+ruxNZOuVHOXw3v1i4744MLDUHwy8VgFQ3FFPxMh5tEKyucWGHAeGjqInFb",
	"xJWG+o4ujs1Dh9reRuOpD5OFwiBkkhsleAPvVu5XfLQ1qG67GJDlkuT+LiEGGB8oma13sMX2n7G5JKQK",
	"64fw7h7I62M+7xo+XbZmwhUP1ZaQM5EdPvz4zW5d2f0A37adiUW8ec0jsdDyphO/pvht2v7tIUwcJuRc",
	"4czbk/ZcSHL7cE8TugJjQ1CNbj7fjNAMpUEyLeiEfrkZ3Xzxh9hu6Z3BktP/WYDXBHTU0/U9QvkjuFvt",
	"jWjdRI1Ho1fdP/UrW5pH5J26JXI/RbKqZtQ+kmijbogtVLswbN+k+VutIsdtqGovFpx2DOX4K/UYPCI1",
	"KBtB6QcDzMGtP3/FYAbr/qb4+mRXdOGrYLN7mbjp7Mrn0y/ZucwKNwenwToAV51ct8HeJCE2hy+Cb4LK",
	"ZuCgi/6db6/Qb+Hx18iBjdYkzMSJLdIUrJ0XWbY+mU/BnLhPyaEse2+S9c+ts+/rj+D2AdC8ZN8jE9sh",
	"w+oSHqlfM5cuu+D9pvm5k6/Sqj4pOPrOUjDAdyAFQyU/bX1gHBaMSO1/IQU5fNnxOk2JnR7bqFbERzbQ",
	"jA84qifxg7OzxHj8xuXCkrPfiG4GRM/2Ty1Ley4Qju7r/rzpK2b7tv6ousVMuozevRWs5FVEclaRPEIf",
	"V4hEL6RvR/ZcYntlZrqSHn8Yfqo0+z38tBqfStr/Pb6iuDfvhy6q78S7fQaJL+G8VCqtxh9C52s7PpDU",
	"99zig9n0DsGP5dX/o+S/n1/eSSsfSff7087lpP/ijPWB9P9avHWoBOjLW/7O0ayqEClMRid0yLSgm8fN",
	"/wIAAP//w8mNrR0xAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
