// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bidon-io/bidon-backend/internal/admin/store"
	"sync"
)

// Ensure, that PasswordGeneratorMock does implement adminstore.PasswordGenerator.
// If this is not the case, regenerate this file with moq.
var _ adminstore.PasswordGenerator = &PasswordGeneratorMock{}

// PasswordGeneratorMock is a mock implementation of adminstore.PasswordGenerator.
//
//	func TestSomethingThatUsesPasswordGenerator(t *testing.T) {
//
//		// make and configure a mocked adminstore.PasswordGenerator
//		mockedPasswordGenerator := &PasswordGeneratorMock{
//			GenerateFunc: func(password string) (string, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedPasswordGenerator in code that requires adminstore.PasswordGenerator
//		// and then make assertions.
//
//	}
type PasswordGeneratorMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(password string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Password is the password argument value.
			Password string
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *PasswordGeneratorMock) Generate(password string) (string, error) {
	if mock.GenerateFunc == nil {
		panic("PasswordGeneratorMock.GenerateFunc: method is nil but PasswordGenerator.Generate was just called")
	}
	callInfo := struct {
		Password string
	}{
		Password: password,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(password)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedPasswordGenerator.GenerateCalls())
func (mock *PasswordGeneratorMock) GenerateCalls() []struct {
	Password string
} {
	var calls []struct {
		Password string
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}
