// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/notification"
	"github.com/bidon-io/bidon-backend/internal/notification/store"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/schema"
	"sync"
)

// Ensure, that AuctionResultRepoMock does implement notification.AuctionResultRepo.
// If this is not the case, regenerate this file with moq.
var _ notification.AuctionResultRepo = &AuctionResultRepoMock{}

// AuctionResultRepoMock is a mock implementation of notification.AuctionResultRepo.
//
//	func TestSomethingThatUsesAuctionResultRepo(t *testing.T) {
//
//		// make and configure a mocked notification.AuctionResultRepo
//		mockedAuctionResultRepo := &AuctionResultRepoMock{
//			CreateOrUpdateFunc: func(ctx context.Context, imp *schema.Imp, bids []store.Bid) error {
//				panic("mock out the CreateOrUpdate method")
//			},
//		}
//
//		// use mockedAuctionResultRepo in code that requires notification.AuctionResultRepo
//		// and then make assertions.
//
//	}
type AuctionResultRepoMock struct {
	// CreateOrUpdateFunc mocks the CreateOrUpdate method.
	CreateOrUpdateFunc func(ctx context.Context, imp *schema.Imp, bids []store.Bid) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrUpdate holds details about calls to the CreateOrUpdate method.
		CreateOrUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Imp is the imp argument value.
			Imp *schema.Imp
			// Bids is the bids argument value.
			Bids []store.Bid
		}
	}
	lockCreateOrUpdate sync.RWMutex
}

// CreateOrUpdate calls CreateOrUpdateFunc.
func (mock *AuctionResultRepoMock) CreateOrUpdate(ctx context.Context, imp *schema.Imp, bids []store.Bid) error {
	if mock.CreateOrUpdateFunc == nil {
		panic("AuctionResultRepoMock.CreateOrUpdateFunc: method is nil but AuctionResultRepo.CreateOrUpdate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Imp  *schema.Imp
		Bids []store.Bid
	}{
		Ctx:  ctx,
		Imp:  imp,
		Bids: bids,
	}
	mock.lockCreateOrUpdate.Lock()
	mock.calls.CreateOrUpdate = append(mock.calls.CreateOrUpdate, callInfo)
	mock.lockCreateOrUpdate.Unlock()
	return mock.CreateOrUpdateFunc(ctx, imp, bids)
}

// CreateOrUpdateCalls gets all the calls that were made to CreateOrUpdate.
// Check the length with:
//
//	len(mockedAuctionResultRepo.CreateOrUpdateCalls())
func (mock *AuctionResultRepoMock) CreateOrUpdateCalls() []struct {
	Ctx  context.Context
	Imp  *schema.Imp
	Bids []store.Bid
} {
	var calls []struct {
		Ctx  context.Context
		Imp  *schema.Imp
		Bids []store.Bid
	}
	mock.lockCreateOrUpdate.RLock()
	calls = mock.calls.CreateOrUpdate
	mock.lockCreateOrUpdate.RUnlock()
	return calls
}
