name: Auto release

on:
  push:
    branches:
      - main

jobs:
  autorelease:
    name: Autorelease
    runs-on: [self-hosted, main]
    steps:
    - name: Get current date
      id: date
      run: |
        echo "date=$(date +'%y%m')" >> $GITHUB_OUTPUT
        echo "date_title=$(date +'%d %b %Y')" >> $GITHUB_OUTPUT
    - name: Count releases
      id: count
      run: |
        echo "count_month=$(curl -u "${{ secrets.USER_APPODEAL_RUNNER }}:${{ secrets.PAT_APPODEAL_RUNNER }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases | jq --arg date $(date +"%Y-%m") -r 'map(select(.created_at | test($date)?)) | length +1')" >> $GITHUB_OUTPUT
        echo "count_day=$(curl -u "${{ secrets.USER_APPODEAL_RUNNER }}:${{ secrets.PAT_APPODEAL_RUNNER }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases | jq --arg date $(date +"%Y-%m-%d") -r 'map(select(.created_at | test($date)?)) | length +1')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.PAT_APPODEAL_RUNNER }}"
        tag: "v${{ steps.date.outputs.date }}.${{ steps.count.outputs.count_month }}.0"
        prerelease: false
        name: "Release ${{ steps.date.outputs.date_title }} #${{ steps.count.outputs.count_day }}"
        generateReleaseNotes: true
