name: Build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'bidon_api/**'
      - 'bidon_back/**'
  release:
    types: [published]

jobs:
  tag:
    name: Set tag
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    runs-on: [self-hosted]
    steps:
      - name: Set tag
        id: tag
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            if '${{ github.event_name }}' == 'push':
                print(f'TAG=${{ github.sha }}'[:8], file=fh)
            elif '${{ github.event_name }}' == 'release':
                print('TAG=${{ github.event.release.tag_name }}', file=fh)
        shell: python

  build:
    name: Build image
    needs: [tag]
    runs-on: [self-hosted]
    env:
      TAG: ${{ needs.tag.outputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        component: [api, back]
    steps:
      - name: Login registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USERNAME_DEPLOY }}
          password: ${{ secrets.REGISTRY_PASSWORD_DEPLOY }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_RUNNER }}
          password: ${{ secrets.PAT_RUNNER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Build and Push image
        run: make docker-build-push-prod-${{ matrix.component }} TAG=$TAG

  migration:
    name: Data migration
    runs-on: [self-hosted]
    needs: [tag, build]
    env:
      TAG: ${{ needs.tag.outputs.tag }}
    if: always() && needs.build.result == 'success'
    steps:
      - name: Checks-out repository devops
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.ANSIBLE_SECRET }}/devops
          token: ${{ secrets.PAT_RUNNER }}

      - name: Deploy
        working-directory: ./${{ secrets.ANSIBLE_SECRET }}/prod
        run: make bidon-data-migratio TAG=$TAG

  deploy:
    name: Deploy
    runs-on: [self-hosted]
    needs: [tag, migration]
    env:
      TAG: ${{ needs.tag.outputs.tag }}
    if: always() && needs.migration.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        component: [api, backend]
    steps:
      - name: Checks-out repository devops
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.ANSIBLE_SECRET }}/devops
          token: ${{ secrets.PAT_RUNNER }}

      - name: Deploy
        working-directory: ./${{ secrets.ANSIBLE_SECRET }}/prod
        run: make bidon-${{ matrix.component }} TAG=$TAG
