name: Deploy bidon-admin K8S

on:
  # workflow_call:
  #   inputs:
  #     tag:
  #       type: string
  #       required: true
  #       default: latest
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       type: string
  #       required: true
  #       default: latest
  push:
    branches:
      - "DO-2683/bidon-app-helm-deploy"

jobs:
  deploy:
    name: Deploy bidon-admin K8S
    runs-on: [self-hosted]
    environment: production
    env:
      TAG: ${{ 'latest' }}
    steps:
      # - name: Get latest release
      #   if: ${{ inputs.tag == 'latest' }}
      #   id: latest-release
      #   uses: octokit/request-action@v2.1.7
      #   with:
      #     route: GET /repos/${{ github.repository }}/releases/latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_RUNNER }}

      # - name: Set TAG
      #   if: ${{ inputs.tag == 'latest' }}
      #   run: echo "TAG=${{ fromJson(steps.latest-release.outputs.data).tag_name }}" >> $GITHUB_ENV

      - name: Checks-out repository devops
        uses: actions/checkout@v4
        with:
          repository: bidon-io/devops
          ref: DO-2683/bidon-app-helm-deploy
          token: ${{ secrets.PAT_RUNNER }}

      - name: Deploy admin
        working-directory: ./prod
        run: ANSIBLE_VAULT_PASSWORD_FILE=$ANSIBLE_VAULT_PASSWORD_FILE_BIDON && make k8s-bidon-app-bidon-admin TAG=$TAG
