name: Scan repo
on:
  push:
    branches:
#     - master
jobs:
  trivy:
    name: Vulnerability scanning
    runs-on: [self-hosted]
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Run Trivy
        run: docker run --rm -v $(pwd):/opt/project aquasec/trivy fs --scanners vuln --format github /opt/project
        
